### ISSUE TITLE
You can't use /msg across servers (between survival and creative for example)

### ISSUE THREAD

**Issue by Markusi13** [PirateCraft/dev#10]
**Describe the bug** *(A clear and concise description of what the bug is)*:
When i'm on creative server and try to message someone on survival using /msg (username), the person on survival doesn't recieve a message. If you send the messag it also doesn't show any error in chat or anything else.

**To Reproduce** *(Steps to reproduce the behavior)*:
Have a player on survival, go to creative and message that person.

**Time and Date** *(If applicable, add the time (in GMT+1) and date (DD.MM.YYYY) of the issue)*:
12.08.2020 | 11:22

**Comment by CreatingWithKass** [comment]
In addition to this /msg problem, you cannot /msg anyone who is on the Creative server with you. So /msg doesn't work across servers or on Creative in general.

**Comment by TomLewis** [comment]
Fixed on Sep 13th https://discordapp.com/channels/139382225375330305/545688946143657985/754657192107311134
