### ISSUE TITLE
**This is a /Server Play bug** Players are able to get on top of the arena (i.e on the barrier blocks). (ROLEYMOLEYOLEY)

### ISSUE THREAD

**Issue by CreatingWithKass** [PirateCraft/dev#103]
**Describe the bug** *(A clear and concise description of what the bug is)*:
Players are able to parkour/e-pearl in a certain path to get on top of the barrier blocks in /server play. 

**To Reproduce** *(Steps to reproduce the behavior)*:
Follow the YouTube video steps. 

**Time and Date** *(If applicable, add the time (in GMT+1) and date (DD.MM.YYYY) of the issue)*:
11/12/2020 

**Screenshots/Videos (Delete if not needed)** *(If applicable, add screenshots/videos to help explain your problem)*:
https://youtu.be/6jes9PA08ao

**Comment by TomLewis** [comment]
haha Magic! I like that great jump you made to get onto one block.

**Comment by CreatingWithKass** [comment]
> haha Magic! I like that great jump you made to get onto one block.

Ikr, the entire time I was recording I was like 'Oh god, don't miss this pearl. Is that a five-block jump?!" Lol! I'm actually really bad at parkour.

**Comment by TomLewis** [comment]
Love it.

So this just needs updating, thing is. I want to do this properly.

I want it so builders can copy builds between Creative/Play at will and make them working arenas.
Plus that FFA is terrible, I want to replace the plugin that does FFA entirely.

So until then super low priority, but its listed as a Todo for when builders can just update arenas.

**Comment by Mrlimethewise** [comment]
can't be fixed till server play is back
