### ISSUE TITLE
Custom tab list from /server play is retained when logging into survival (PIPPIP5789)

### ISSUE THREAD

**Issue by IwanIDev** [PirateCraft/dev#104]
**Describe the bug** *(A clear and concise description of what the bug is)*:
After playing a few rounds on /server play, the Tab list on survival shows all of the correct players, however it still shows the custom parts of the tab list from server play (photo shows in better detail)

**To Reproduce** *(Steps to reproduce the behavior)*:
1. Play a few rounds on /server play
2. Return to survival using /server survival
3. Check tab list

**Time and Date** *(If applicable, add the time (in GMT+1) and date (DD.MM.YYYY) of the issue)*:
First reported 15.12.2020 at 03:56 GMT+1

**Screenshots/Videos (Delete if not needed)** *(If applicable, add screenshots/videos to help explain your problem)*:
![Image of issue](https://cdn.discordapp.com/attachments/744927959764434974/788238082817785896/2020-12-14_20.53.30.png)

**Comment by TomLewis** [comment]
Thats the same with every single server that uses a custom tab-list, its just cached by the client.
Log out the server and log back in again, or close minecraft and re-open.
