### ISSUE TITLE
Game deleted all 3 sethomes of a boatswain when they accidentally typed "/delhome 1" twice. 

### ISSUE THREAD

**Issue by CreatingWithKass** [PirateCraft/dev#109]
**Describe the bug** *(A clear and concise description of what the bug is)*:
A boatswain named Harbinger787 apparently typed "/delhome 1" twice on accident and it deleted all 2 /sethomes. I asked to make sure they didn't accidentally do /delhome without the name, but they insist they didn't. 

**To Reproduce** *(Steps to reproduce the behavior)*:
Do /delhome (name) twice in quick succession. Hard to test without losing homes. 

**Time and Date** *(If applicable, add the time (in GMT+1) and date (DD.MM.YYYY) of the issue)*:
02/01/2020

**Comment by TomLewis** [comment]
This isnt a bug, this is just "retard player". Wontfix.
