### ISSUE TITLE
The Wiki & Forums page seem to only work at chance for certain players. 

### ISSUE THREAD

**Issue by CreatingWithKass** [PirateCraft/dev#11]
**Describe the bug** 
Basically, when I try to log into the Forums I almost every time get a "504 Error" screen, which indicates that my browser as well as CloudFlare are working, but the connection timed out when it tried to connect to the host (PirateCraft). 

**To Reproduce** *(Steps to reproduce the behavior)*:
I simply try to log into the forums. Sometimes it happens when I try to click on channels as well, it'll load for a moment and then return to the error page. 

**Time and Date** *(If applicable, add the time (in GMT+1) and date (DD.MM.YYYY) of the issue)*:
August 10th, 11th, 12th (2020); basically all day. 

**Screenshots/Videos (Delete if not needed)** *(If applicable, add screenshots/videos to help explain your problem)*:
![gatewaytimeout](https://user-images.githubusercontent.com/69595267/90040817-6bcca400-dc96-11ea-9211-6cbcf1497dcc.PNG)

**Comment by Markusi13** [comment]
GodsDead yesterday at 22:01 via discord:
`Whoever asked about the website, weve hit our 90% use for CPU and inode limit
so they throttle it`

Can't be fixed by us.
