### ISSUE TITLE
Typo when a player does /market, it says "maket" instead. (Capt_Lugnut)

### ISSUE THREAD

**Issue by CreatingWithKass** [PirateCraft/dev#111]
**Describe the bug** *(A clear and concise description of what the bug is)*:
When a player does /market, it pops up a message "Please select the Pirate maket to warp to." Maket should be changed to Market. 

**To Reproduce** *(Steps to reproduce the behavior)*:
Type /marketplace in chat. It'll show then. 

**Time and Date** *(If applicable, add the time (in GMT+1) and date (DD.MM.YYYY) of the issue)*:
07/01/2021 

**Screenshots/Videos (Delete if not needed)** *(If applicable, add screenshots/videos to help explain your problem)*:
![typo](https://user-images.githubusercontent.com/69595267/104102614-cb41d680-526b-11eb-8fe6-20220f2251af.png)

**Comment by TomLewis** [comment]
Fixed! my fingers move too fast sometimes when typing and I miss letrs.
