### ISSUE TITLE
Players that do /warp FFA are invincible on /server play and can kill other players but can't take damage themselves. (IcyWizard1)

### ISSUE THREAD

**Issue by CreatingWithKass** [PirateCraft/dev#112]
**Describe the bug** *(A clear and concise description of what the bug is)*:
On /server play, you can do /warp freeforall. When doing so, you are put into the FFA server. You are invincible, meaning people can't hit you but you **can** hit them. This allows players to kill others without taking a single hit.

**To Reproduce** *(Steps to reproduce the behavior)*:
 Do /server play. Have a tester click the FFA NPC to join normally, and then the second tester do /warp FFA, then fight. The person that did /warp FFA will be able to kill the first tester, but the first tester will not be able to harm them. 

**Time and Date** *(If applicable, add the time (in GMT+1) and date (DD.MM.YYYY) of the issue)*:
17/01/21

**Screenshots/Videos (Delete if not needed)** *(If applicable, add screenshots/videos to help explain your problem)*:
https://youtu.be/btXxD_EExPo

**Comment by TomLewis** [comment]
They should not have access to /warp freeforall, that was for building only.
This is only because they are not actually in the game and they have used an admin warp to get to the location. Nothing else.
There is no permission giving them /warp freeforall, so I have no idea how they have access.

**Comment by CreatingWithKass** [comment]
> They should not have access to /warp freeforall, that was for building only.
> This is only because they are not actually in the game and they have used an admin warp to get to the location. Nothing else.
> There is no permission giving them /warp freeforall, so I have no idea how they have access.

Interesting. The moderation team will police it for now, until this can be sorted

**Comment by TomLewis** [comment]
Was this bug resolved when I updated the play servers permissions to be inherited from the main survival?

**Comment by CreatingWithKass** [comment]
> Was this bug resolved when I updated the play servers permissions to be inherited from the main survival?

The command is now blocked, it says I do not have permission. This bug is resolved.
