### ISSUE TITLE
When mining with Eff V and Haste II (instantly mining stone), players sometimes get kicked for "unusually interacting with blocks or entities"

### ISSUE THREAD

**Issue by CreatingWithKass** [PirateCraft/dev#115]
**Describe the bug** *(A clear and concise description of what the bug is)*:
When a player is instantly mining a block (stone) using Efficiency V and Haste II, they are kicked for "Unusually interacting with blocks or entities" 
1.16.5 

**To Reproduce** *(Steps to reproduce the behavior)*:
Use a beacon to get Haste II and a pickaxe with Eff V and mine stone quickly. You may be kicked by the anticheat for unusually interacting with blocks or entities. 

**Time and Date** *(If applicable, add the time (in GMT+1) and date (DD.MM.YYYY) of the issue)*:
01/02/2021 

**Screenshots/Videos (Delete if not needed)** *(If applicable, add screenshots/videos to help explain your problem)*:
![image](https://user-images.githubusercontent.com/69595267/106545121-d12b8000-64d6-11eb-9487-dfd782f47afc.png)

**Comment by CreatingWithKass** [comment]
I will use this thread to collect similar bugs for Encode. 

1.  Description: **Spam crouching or crouching/uncrouching** while mining netherrack instantly (eff V pickaxe) makes you get kicked for "unusually interacting with blocks or entities!:
Version: 1.16.5
How to reproduce: mine in the nether with a god pick and crouch. 

2.  Description: Rapidly harvest crops with hand, kicks you for "Unusually interacting with blocks or entities". This occurs almost every time I harvest crops, and often multiple occurrences within 5 minutes of eachother.
Version: 1.12.2
How to reproduce: Break crops (wheat/potatoes/carrots) rapidly with anything faster than your hand.

3.

**Comment by TomLewis** [comment]
Anything Anticheat based will need to be re-checked as I recently updated a few times since this issue was made!
