### ISSUE TITLE
When a player drinks a Santa's Brew potion (levitation), it sometimes causes teleports the player back to their original spot when the effect wears off. (Mindmeld420)

### ISSUE THREAD

**Issue by CreatingWithKass** [PirateCraft/dev#116]
**Describe the bug** *(A clear and concise description of what the bug is)*:
When a player drinks a levitation brew, it will levitate them up until the effect wears off - and then **sometimes** the player will be teleported back to where they were standing when they drank the potion. I tested this multiple times and it only happened once; seems completely random. 
**Version:** All 

**To Reproduce** *(Steps to reproduce the behavior)*:
Drink a potion (such as Santa's Brew) that gives levitation. Once the effect wears off, you may be teleported back to where you initially drank the potion. 

**Time and Date** *(If applicable, add the time (in GMT+1) and date (DD.MM.YYYY) of the issue)*:
10/02/2021 

**Screenshots/Videos (Delete if not needed)** *(If applicable, add screenshots/videos to help explain your problem)*:
https://youtu.be/4FOS6gQQSqQ

**Comment by CreatingWithKass** [comment]
Maybe this has something to do with the same bug that TPs players back when exiting boats or using sponges?
This particular bug happens in all versions (tested in 1.12.2 and 1.16.4)

**Comment by TomLewis** [comment]
Yeah this definitely fits in with #113 
I will mark as dupe for now until we can figure out what the hell is doing it!
