### ISSUE TITLE
When a player /tops onto a fence or cobble wall, they fall through it as if the block is not there. (EisenGraf)

### ISSUE THREAD

**Issue by CreatingWithKass** [PirateCraft/dev#117]
**Describe the bug** *(A clear and concise description of what the bug is)*:
Players can only /top onto physical blocks via the plugin; so when a player /tops under a fence or cobble wall, it allows them to TP to the top of that fence. However, immediately after its as if the block is no longer registered and they fall straight through, back to where they originally were. 

**To Reproduce** *(Steps to reproduce the behavior)*:
Stand beneath a fence or cobble wall and /top. You will TP on the fence, then fall straight through. 

**Time and Date** *(If applicable, add the time (in GMT+1) and date (DD.MM.YYYY) of the issue)*:
28/2/2021

**Screenshots/Videos (Delete if not needed)** *(If applicable, add screenshots/videos to help explain your problem)*:
https://youtu.be/TlFSfKrtD1U

**Additional context (Delete if this isn't needed)** *(Add any other context about the problem here)*:
**We tested this bug.**
It seems to only happen if the fence or cobble wall is **one thick.** If you stack a fence on top of another fence and then /top, it places you on top of the fences without a problem. Could be conflicting plugins, or that it for some reason registers the fence as enough to /top with but then just... doesn't once the command is successful.

**Comment by TomLewis** [comment]
Should be fixed in this update:
https://discord.com/channels/139382225375330305/545688946143657985/836530235024605264
