### ISSUE TITLE
Mortar cannons (when using a lead and shooting a player up) will insta-kill you. (Palmerto)

### ISSUE THREAD

**Issue by CreatingWithKass** [PirateCraft/dev#118]
**Describe the bug** *(A clear and concise description of what the bug is)*:
With mortars, players can use a lead and click the mortar to then place themselves as the projectile. This normally shoots the player very high in the air but does not lead to their death upon landing. In this case, the player insta-died, and was kicked after for **Flying is not enabled on this server**. After more testing, this happens **every time a mortar is used.**

**To Reproduce** *(Steps to reproduce the behavior)*:
Use a mortar cannon and lead projectile to shoot yourself high in the air. It will insta-kill you & you will be kicked from the server for **"Flying is not enabled on this server".** 

**Time and Date** *(If applicable, add the time (in GMT+1) and date (DD.MM.YYYY) of the issue)*:
14/2/2021 

**Screenshots/Videos (Delete if not needed)** *(If applicable, add screenshots/videos to help explain your problem)*:
https://youtu.be/e7zan3ucPvw

&

https://youtu.be/qMM4M5HkJxw

**Comment by TomLewis** [comment]
Now that is interesting, That properly yeets you into the sky! The velocity of a mortar is only 0.3 more than an iron cannon, I wonder if it's the angle then.

Can we have all the other cannons checked first, then we will know if its angle/velocity of the projectile or the cannon multipliers.

**Comment by CreatingWithKass** [comment]
> Now that is interesting, That properly yeets you into the sky! The velocity of a mortar is only 0.3 more than an iron cannon, I wonder if it's the angle then.
> 
> Can we have all the other cannons checked first, then we will know if its angle/velocity of the projectile or the cannon multipliers.

I tried with a few other cannon types, it did not instant kill or kick. However, when trying the mortar again, it would occasionally kick me and a friend for flying, and then we would die upon re-logging from fall damage. It did not instant kill me and then kick though, so now it just seems to be the anti-cheat.
