### ISSUE TITLE
Zombies are spawning on non-spawnable/non-full blocks (i.e. slabs and inside walls of chests). (Capt_Lugnut)

### ISSUE THREAD

**Issue by CreatingWithKass** [PirateCraft/dev#119]
**Describe the bug** *(A clear and concise description of what the bug is)*:
While I have not managed to reproduce, reports say that zombies sometimes spawn on areas they should not be able to spawn in - like slabs and walls of chests. **This could have something to do with the increased spawnrate that was added around the time of this bug's reporting.** 

**To Reproduce** *(Steps to reproduce the behavior)*:
Stand in a village/next to a village that has no spawnable blocks within range. Watch slabs or walls of chests, zombies will most likely spawn there. 

**Time and Date** *(If applicable, add the time (in GMT+1) and date (DD.MM.YYYY) of the issue)*:
30/1/2021

**Comment by TomLewis** [comment]
Will require a reason to need to fix if it is an issue.
For now wont fix.
