### ISSUE TITLE
Custom death message says “hoard” while it should say “horde” (when killed by zombies)

### ISSUE THREAD

**Issue by EnderSold** [PirateCraft/dev#12]
**Describe the bug** *(A clear and concise description of what the bug is)*:
When you get killed by zombies the deathmessage says `(user) failed to stop the zombie hoard`, but it's horde not hoard.

**To Reproduce** *(Steps to reproduce the behavior)*:
Get killed by a horde of zombies.

**Time and Date** *(If applicable, add the time (in GMT+1) and date (DD.MM.YYYY) of the issue)*:
n/a

**Screenshots/Videos (Delete if not needed)** *(If applicable, add screenshots/videos to help explain your problem)*:
![image0](https://user-images.githubusercontent.com/13572005/90043241-23c87400-dccc-11ea-8d04-8f516612b7e3.jpg)

**Comment by FrozenBeard** [comment]
Fixed.
