### ISSUE TITLE
Creative will not allow players to drop items, but chests breaking will drop items in chest (IronAR)

### ISSUE THREAD

**Issue by IwanIDev** [PirateCraft/dev#123]
**Describe the bug** *(A clear and concise description of what the bug is)*:
When on creative server, all ranks tested cannot drop items, in any plots, even their own. An error (I believe to be coming from worldguard, but that is speculation) appears in chat when you attempt it. Placing items in chests and breaking the chests does drop items, however.

**To Reproduce** *(Steps to reproduce the behavior)*:
1. Go onto creative server
2. Obtain an item
3. Attempt to drop said item. 

**Time and Date** *(If applicable, add the time (in GMT+1) and date (DD.MM.YYYY) of the issue)*:
10.03.2021 at 11:23 GMT+1

**Screenshots/Videos (Delete if not needed)** *(If applicable, add screenshots/videos to help explain your problem)*:
![Items from chest](https://i.imgur.com/yZ6eJLT.png) Shows items that were placed in a chest, and the chest was broken.
![Items dropped by player](https://i.imgur.com/84M8e7h.png) Shows me attempting to drop items in my own region. Error is shown.

**Comment by TomLewis** [comment]
Yeah, people were dropping items that can kill people in creative mode! Gotta love players! 
Gotta love Mojang making Creative entirely client side! What could go wrong!

Easiest solution I can think of would be to also block `item-pickup` and just let items despawn, and bump the despawn timer to something higher.

**Comment by TomLewis** [comment]
Disabled `item-pickup` on Creative & Ocean worlds.
