### ISSUE TITLE
On creative, you can get silverfish to spawn by breaking "infested blocks" and spawn shulker boxes with world edit. (Bombniks)

### ISSUE THREAD

**Issue by CreatingWithKass** [PirateCraft/dev#124]
**Describe the bug** *(A clear and concise description of what the bug is)*:
On creative, spawning mobs or placing shulker boxes is disabled. However, if you place an "infested block" and then break it, the block spawns a silverfish. This can be used to lag the server. 
If you use w/e, you can select an area and spawn a shulker box, something that is disabled on creative. It can be used. When selecting a massive area, the player can make a lot of shulker boxes and then start breaking them, causing entity lag as they drop upon breaking. The game also bugs out and shows the shulker boxes turning to grass when you break them, and eventually kicks the player if they do too many at once. 

**To Reproduce** *(Steps to reproduce the behavior)*:
Place an infested block in creative and then break it. It will spawn silver fish. 
Use w/e's command //set blue_shulker_box OR hold the shulker and type //set hand; it will spawn the shulker box. 

**Time and Date** *(If applicable, add the time (in GMT+1) and date (DD.MM.YYYY) of the issue)*:
27/04/2020 

**Screenshots/Videos (Delete if not needed)** *(If applicable, add screenshots/videos to help explain your problem)*:
https://youtu.be/rAJkHFaRixA

**Comment by MionaTheGreat** [comment]
Infested blocks have been blocked from creative

**Comment by Bombniks** [comment]
Shulkers can also be placed via a dispenser

**Comment by Mrlimethewise** [comment]
not fixable till creative is back
