### ISSUE TITLE
Players cannot use some commands while global chat is muted. (Espul)

### ISSUE THREAD

**Issue by CreatingWithKass** [PirateCraft/dev#125]
**Describe the bug** *(A clear and concise description of what the bug is)*:
When moderators+ mute the global chat, many commands do not work. These are some but not limited to: 
/home, /r and /msg 

**To Reproduce** *(Steps to reproduce the behavior)*:
Have moderator+ mute global chat, then test comands. 

**Time and Date** *(If applicable, add the time (in GMT+1) and date (DD.MM.YYYY) of the issue)*:
13/3/2021

**Comment by TomLewis** [comment]
I looked into this a while back, no idea why. The chat plugin needs to be entirely re-made from scratch which is on my to-do so once you see that I've done that in the changelogs re-test this.
