### ISSUE TITLE
Players can use /cmi commands on /server play. (Jakkeyyy) 

### ISSUE THREAD

**Issue by CreatingWithKass** [PirateCraft/dev#126]
**Describe the bug** *(A clear and concise description of what the bug is)*:
Commands are turned off on server play, and with good reason. However, players are able to use /cmi commands to do things like teleport, etc. 

**To Reproduce** *(Steps to reproduce the behavior)*:
Go on server play and do /cmi ; it will allow anyone, not just staff, to use those commands. People have teleported out of fights this way, from someone outside of the fight doing /cmi tpahere (name) 

**Time and Date** *(If applicable, add the time (in GMT+1) and date (DD.MM.YYYY) of the issue)*:
21/3/2021

**Screenshots/Videos (Delete if not needed)** *(If applicable, add screenshots/videos to help explain your problem)*:
https://youtu.be/5qV9A0GdDyU

**Comment by TomLewis** [comment]
Removed it from server.
