### ISSUE TITLE
On the PMC store, it says that the currency version of 5k claimblocks is 3k, which is wrong since 1 claimblock sells for $.5 now instead of $.6  (Tulipss)

### ISSUE THREAD

**Issue by CreatingWithKass** [PirateCraft/dev#129]
**Describe the bug** *(A clear and concise description of what the bug is)*:
Claimblocks used to sell for $.6 each, but now they sell for $.5; on the store, we need to update the message to be the accurate pricing for 5k claimblocks sold equals $2,500 not $3,000. 

**To Reproduce** *(Steps to reproduce the behavior)*:
Check store. 

**Time and Date** *(If applicable, add the time (in GMT+1) and date (DD.MM.YYYY) of the issue)*:
01/04/2021

**Screenshots/Videos (Delete if not needed)** *(If applicable, add screenshots/videos to help explain your problem)*:
![claimblock](https://user-images.githubusercontent.com/69595267/116818611-50623b80-ab3a-11eb-809b-179256fbcfbf.PNG)

**Comment by TomLewis** [comment]
Yes, this is a VERY legacy version of the store. Ive already re-made the store from scratch, I just need to complete a few more jobs in-game before I can start work on this job again of making the new store live.
its why things in the store do not work too.
