### ISSUE TITLE
/warp east's spawn location is 1 spot below the ground and it glitches then kicks the player. (IronAR & Notateabaq)

### ISSUE THREAD

**Issue by CreatingWithKass** [PirateCraft/dev#135]
**Describe the bug** *(A clear and concise description of what the bug is)*:
When a player does /warp east, they are teleported one block below the ground and glitch into the ground. This then causes them to be kicked for flying. 

**To Reproduce** *(Steps to reproduce the behavior)*:
Do /warp east

**Time and Date** *(If applicable, add the time (in GMT+1) and date (DD.MM.YYYY) of the issue)*:
14/5/2021

**Additional context (Delete if this isn't needed)** *(Add any other context about the problem here)*:
Probably just need to move the spawn location up one block.

**Comment by Mrlimethewise** [comment]
this seems to happen due to minor lag
