### ISSUE TITLE
Not being able to send messages through ! on creative. (Tulipss)

### ISSUE THREAD

**Issue by TheAcusa** [PirateCraft/dev#136]
This bug will not allow you to talk to people on survival/server play through creative when using !.

Type !(message) on creative.

(GMT-6) (18/5/2021)
 ![118742584-52085080-b816-11eb-981d-6617dc1c33cf 1](https://user-images.githubusercontent.com/84421057/118897384-c05d1980-b8cf-11eb-854c-e8a96c413f84.png)

**Comment by TheAcusa** [comment]
https://user-images.githubusercontent.com/84421057/118742584-52085080-b816-11eb-981d-6617dc1c33cf.png
^
That's the link it for some reason didn't put it on there.

**Comment by Mrlimethewise** [comment]
unfixable until creative is back
