### ISSUE TITLE
/nv and /bu stopped working on creative.(Pjeturr)

### ISSUE THREAD

**Issue by TheAcusa** [PirateCraft/dev#138]
/nv and /bu stopped working on creative.

Do /nv and /bu on creative.

(GMT-6, 5:09pm) (19/05/2021)

**Comment by TomLewis** [comment]
Related: https://github.com/PirateCraft/dev/issues/121

I never got a reply, so I have added the plugin back onto creative.

So not sure if it ever fixed that other ticket.
