### ISSUE TITLE
Book and Quill's glitch out buy/sell signs when in trapped chests (ScriptX)

### ISSUE THREAD

**Issue by Bombniks** [PirateCraft/dev#140]
**Describe the bug** : When book and quill's are placed in a trapped chest and linked up to a sell/buy sign, the sign glitches out and goes red after 1-5 hours

**To Reproduce** : Place some Book And Quill's in a trapped chest and then link it to a sell or a buy sign, then wait some time, around 1-5 hours normally and the sign turns red even though there are still Books in the chest, re-linking the chest makes it blue again

**Time and Date** : Tested 22/5/2021, Reported 6/5/2021

**Screenshots/Videos*:
![2021-05-22_12 40 49](https://user-images.githubusercontent.com/84421181/119225834-ec1a1280-bb0e-11eb-9b37-341724182ac5.png) Trapped Chest full of Book and Quill's
![2021-05-22_12 40 53](https://user-images.githubusercontent.com/84421181/119225863-0653f080-bb0f-11eb-8d49-271d85df7d6b.png)
The sign is red even though the chest is full

**Additional context**: Tested with the help of ScriptX in his shop, normal chest are fine trapped are the problem

**Comment by Mrlimethewise** [comment]
fixed!
