### ISSUE TITLE
Can't put water into invintory on creative(PandamoniumPrime)

### ISSUE THREAD

**Issue by TheAcusa** [PirateCraft/dev#141]
Won't let you put water into inventory.

Try to put water into inventory.

(-6 GMT) (8:15PM) (29/5/21)

![image](https://user-images.githubusercontent.com/84421057/120088893-dbdbd780-c0ba-11eb-880e-34f54df0a901.png)

**Comment by Mrlimethewise** [comment]
won't be fixable till creative  is back
