### ISSUE TITLE
The new crate's 5-star drop "Colonels Chicken Recipe" Has no custom lore or name when won (davidj123456)

### ISSUE THREAD

**Issue by Bombniks** [PirateCraft/dev#142]
**Describe the bug**: The drop from the new spring crate "Colonels Chicken Recipe"(5-star) has no lore or name when dropped, it's as if is a normal chicken spawn egg, no custom name or lore.

**To Reproduce**: Win a "Colonels Chicken Recipe" from the new spring crate

**Time and Date** : reported on 16:32 GMT +1 4/5/2021
 
**Screenshots/Videos** :
![egg](https://user-images.githubusercontent.com/84421181/120833984-1a660c00-c56b-11eb-9065-6a54e1c832c7.png) - "Colonels Chicken Recipe" when won

**Comment by TomLewis** [comment]
it does when you spawn the egg, the actual item is when you spawn it.
Which creates a chicken with a custom lore AND when you kill it there are 2 separate items that have custom lore & names.
You need to spawn it.
