### ISSUE TITLE
flying in a straight line with /speed 10 gets you kicked for movement hacks by Anticheat (DUPLQ)

### ISSUE THREAD

**Issue by Bombniks** [PirateCraft/dev#147]
**Describe the bug**: You get kicked from Anticheat for movement hacks in creative when you activate /speed 10 and fly in a straight line for a bit.

**To Reproduce**: run /speed 10 while flying to change flying speed to 10, then fly in a straight line for some time. You will eventually start to lag back and then get kicked for "movement related hacks"

**Time and Date**: Tested 21:55 GMT +1 8/5/2021

**Comment by TomLewis** [comment]
Then don't use speed 10! you get to pick how fast you go!
