### ISSUE TITLE
When you swim on the surface of the water, it sometimes glitches out and kicks you for fly hacks (Filipino2555)

### ISSUE THREAD

**Issue by CreatingWithKass** [PirateCraft/dev#15]
**Describe the bug** *(A clear and concise description of what the bug is)*:
When using Minecraft versions 1.13+, the swimming ability sometimes glitches out in water (I've noticed it happens directly under blocks as well) and will kick the player for 'fly hacks'. 

**To Reproduce** *(Steps to reproduce the behavior)*:
Enter higher versions of Minecraft and attempt to swim with the new swimming animation. 

**Time and Date** *(If applicable, add the time (in GMT+1) and date (DD.MM.YYYY) of the issue)*:
07/31/2020

**Additional context (Delete if this isn't needed)** *(Add any other context about the problem here)*:
I've tested this a few times, it doesn't always happen, just randomly when the server's being buggy.

**Comment by FrozenBeard** [comment]
Reported. 

https://github.com/jiangdashao/Matrix-Issues/issues/1952

**Comment by TomLewis** [comment]
@CreatingWithKass Can you please re-test this, this should be fixed for a while.

**Comment by Mrlimethewise** [comment]
not happening anymore as server is 1.18
