### ISSUE TITLE
cactus can drop as an item if a block is placed next to it (MionaTheGreat)

### ISSUE THREAD

**Issue by Bombniks** [PirateCraft/dev#153]
**Describe the bug**: Cactus can drop as an item if a block is placed next to it

**To Reproduce**: Place cactus and then another block next to it.

**Screenshots/Videos**: 
![image](https://user-images.githubusercontent.com/84421181/122680611-c01aab80-d1f8-11eb-9fd5-6d7a1ebe5ae5.png)

**Comment by Mrlimethewise** [comment]
Turns Out Cactus will always be broken if a block is placed next to it
only thing that works is dropping or snow powder started on top of each other!
