### ISSUE TITLE
Spelling of "history" is wrong when looking at players via the forums. (IgnFry) 

### ISSUE THREAD

**Issue by CreatingWithKass** [PirateCraft/dev#159]
### Describe the bug

"History" is spelled "Histroy" on the forums when you look up a player. 

### To Reproduce

Go to the PMC Forums and look up a player. 

### Time and Date

28.05.2021

### Screenshots/Videos

![image](https://user-images.githubusercontent.com/69595267/124013664-96a80f80-d9b0-11eb-8ad5-2c6453eb6925.png)

### Additional context

Figured I'd document it as I know we're trying to overhaul all of the forums. VERY low priority.

**Comment by Mrlimethewise** [comment]
fixed now
