### ISSUE TITLE
If you go to /shop7 (Through the portal) it will tp you above the spawning platform. (Endersold)

### ISSUE THREAD

**Issue by CreatingWithKass** [PirateCraft/dev#16]
**Describe the bug** *(A clear and concise description of what the bug is)*:
If you walk through the specific "spot 7" portal, you spawn in the roofing above the platform and have to jump down. 

**To Reproduce** *(Steps to reproduce the behavior)*:
Go to /warp shop and walk through the shop7 portal.

**Time and Date** *(If applicable, add the time (in GMT+1) and date (DD.MM.YYYY) of the issue)*:
8/14/2020

**Screenshots/Videos (Delete if not needed)** *(If applicable, add screenshots/videos to help explain your problem)*:
![warpglitch](https://user-images.githubusercontent.com/69595267/90262360-38b41d00-de1c-11ea-96da-e6af6c065f47.png)

**Additional context (Delete if this isn't needed)** *(Add any other context about the problem here)*:
Tested it again, it's a repeating issue. Works fine if the user types /warp shop7, just not physically walking through the portal.

**Comment by FrozenBeard** [comment]
Fixed.
