### ISSUE TITLE
Players cannot crouch on the top edge of stairs, they must go on the bottom level, making building hard; they are also occasionally kicked for movement related hacks when this occurs. (Kangy_Roo)

### ISSUE THREAD

**Issue by CreatingWithKass** [PirateCraft/dev#161]
### Describe the bug

When crouching on stairs, you can't crouch on the edge, you need to go down the half level, which makes it hard to build on stairs. You then get kicked by anticheat for movement related hacks.

### To Reproduce

Try to crouch on the top half of stairs. 

### Time and Date

22.05.2021

### Screenshots/Videos

https://www.youtube.com/watch?v=6hRfI1oSHq8

**Comment by TomLewis** [comment]
I can only assume it's an AC prevention with the rubber banding.
There is an update for the AC, which I've pushed for this mornings reboot (10:30am) right now! So re-test and see if its fixed if not we can open an issue with the AC.

**Comment by CreatingWithKass** [comment]
> I can only assume it's an AC prevention with the rubber banding.
> 
> There is an update for the AC, which I've pushed for this mornings reboot (10:30am) right now! So re-test and see if its fixed if not we can open an issue with the AC.
> 
> 
> 
> What client version are they using?

They are in 1.16.5. I will test to see if the bug persists

**Comment by Bombniks** [comment]
I have tested it before, quite tricky to recreate and seemed pretty random.

**Comment by TomLewis** [comment]
So if this cant be re-created, ill close for now.
