### ISSUE TITLE
When players go to the no debuffs gamemode, if they put their sword in the 1st slot of hotbar and eat soup in offhand, sword turns into soup

### ISSUE THREAD

**Issue by CreatingWithKass** [PirateCraft/dev#162]
### Describe the bug

When a player goes into the 'no debuffs' duel gamemode on /server play, and puts their sword in the first slot of their main hand and a soup in their offhand, and then eats said soup, it causes their sword to turn into soup/empty bowl. 

### To Reproduce

Go to server play and try the no debuffs gamemode, eat soup in your offhand while holding a sword in the first slot of your main hand. 

### Time and Date

12.05.2021

### Screenshots/Videos

https://youtu.be/EjEcKSl2-5g

**Comment by Mrlimethewise** [comment]
Unfixable till server play is back
