### ISSUE TITLE
any command with /info returns a worledit error when it's supposed to show custom text

### ISSUE THREAD

**Issue by Bombniks** [PirateCraft/dev#166]
### Describe the bug

trying to run any command with /info (such as /info, /info siege etc.) results in a worldedit permissions lacking error instead of custom texts showing.

### To Reproduce

try running any command  with /info (example: /info siege 2)

### Screenshots/Videos

![image](https://user-images.githubusercontent.com/84421181/127231095-6f39c797-9367-40cb-968d-7269cbb5c085.png)
trying to run /info siege 2

**Comment by Mrlimethewise** [comment]
Doesn't show world edit! anymore
