### ISSUE TITLE
When doing a calculation where 2 or more numbers have decimals with /calc there will be a "do not advertise other websites" chat message/error.

### ISSUE THREAD

**Issue by Bombniks** [PirateCraft/dev#167]
### Describe the bug

When trying to do a calculation where 2 or more of the numbers have decimals with /calc it will not calculate but instead will show up the "do not advertise other websites or IPs" error message. This will not occur if only one of the numbers includes decimals, only if it's 2 or more.
example: 2.84 * 8 won't trigger the error message but 2.84 * 8.0 will trigger it.

### To Reproduce

Just try to calculate something where 2 or more numbers have decimals with /calc, like 5.24 * 9.3415, etc.

**Comment by TomLewis** [comment]
Dupe: https://github.com/PirateCraft/dev/issues/172

Closed.
