### ISSUE TITLE
Palmerto is unable to make a new Big Door even though he has not hit his limit. (Palmerto) 

### ISSUE THREAD

**Issue by CreatingWithKass** [PirateCraft/dev#168]
### Describe the bug

Palmerto, at boatswain, bad 6 big doors. When he ranked up to firstmate (and soon after, Captain), he deleted one of the 6 and tried to re-create it. However, when he tried to create the door, it said he had reached his limit. 

### To Reproduce

Seems to be just Palmerto, as I can't reproduce this. I've asked multiple times for more information but this is what we have to work with - I am logging it here so we can speak with him and try to figure out if this is a personal issue or not. 

### Time and Date

May 19th, 2021

**Comment by TomLewis** [comment]
Did this resolve itself?
