### ISSUE TITLE
When someone is killed, it shows their death on live map - and it shows the killer's crew as the one who died, not their crew. 

### ISSUE THREAD

**Issue by CreatingWithKass** [PirateCraft/dev#169]
### Describe the bug

When someone is killed, the live map shows where they died. It also shows who killed them, and next to the name of the killer it is supposed to show their crew. However, it shows the killer's crew as the killed's crew. 

Example: I killed Bombniks, I am in VAL, he is in REE - but next to my name on live map it shows that I am in "REE". 

### To Reproduce

Kill someone of a different crew, then check the death on live map. It will show the wrong crew tag for you. 

### Time and Date

July 9th, 2021

### Screenshots/Videos

![image](https://user-images.githubusercontent.com/69595267/128616986-91883db9-261c-4c73-8856-ca4b44e4ec5f.png)

**Comment by TomLewis** [comment]
From the config:
```format: "[{vtag}] &f{victim}|&7Killed by: [{atag}] &7{attacker}&7"      # Variables: {victim}, {attacker}, {vtag}, {atag}, Colors: &1, New line is pipe symbol: |```

I cant actually see that image, its too blurred to check, the tags are correct in the cofig, being victim and attacker, and victimtag and attackertag.

Are they backwards? did the developer make the vtag the atag, and the atag the vtag?

If so its a bug for the plugin, I just cant see the image.
