### ISSUE TITLE
If a player goes to a /home while at the end, NEVER leaving the end spawn ship, the ender dragon screen message pops up at their /home. (Lullaby93)

### ISSUE THREAD

**Issue by CreatingWithKass** [PirateCraft/dev#170]
### Describe the bug

When a player goes to /warp end, and does NOT leave the End spawn ship and instead goes back to one of their /homes, it shows the on-screen message of whether or not there is a dragon protecting the End at their sethome. 

### To Reproduce

Do /warp end, and then without moving, do /home. When you return to your home, the message meant for the End will pop up on screen at your sethome. 

### Time and Date

July 16th, 2021

### Screenshots/Videos

https://www.youtube.com/watch?v=wZGJV_rxiSs

**Comment by TomLewis** [comment]
Just timing, when you enter that region it triggers a command to display a title, leaving and re-entering just triggers the command and it takes a second to be sent to you.
