### ISSUE TITLE
In shops, trapdoors that are placed vertically can be opened by placing redstone next to them - even if they aren't trusted to the shop. (EndCrystals_69)

### ISSUE THREAD

**Issue by CreatingWithKass** [PirateCraft/dev#173]
### Describe the bug

Some people use trapdoors as shelf legs or other decoration at shop. When they are placed vertically, they can be opened by anyone that places redstone next to them - even by those not trusted to the shop. This does not work with horizontal trapdoors, like ones used to block basements. 

### To Reproduce

Go to /shop2 Mystic's shop and place redstone next to the wooden trapdoors on the second floor next to the diamond armor. It will open the trapdoors, even if you're not trusted. 

### Screenshots/Videos

https://www.youtube.com/watch?v=KkQpuKLMXiQ

**Comment by TomLewis** [comment]
The shops use WorldGuard regions, so i'm going to assume its a bug with WG, which I cannot update until we go to 1.13+.

Ill keep this open and when the time comes this ticket can be re-checked.

**Comment by Mrlimethewise** [comment]
clarified from ae0n too people don't have perms to achieve this anymore
