### ISSUE TITLE
Hotkeys no longer work in survival (or test). (Nationalistic) 

### ISSUE THREAD

**Issue by CreatingWithKass** [PirateCraft/dev#19]
**Describe the bug** *(A clear and concise description of what the bug is)*:
When a player tries to use designated hotkeys, they simply do not work. The item that was moved returns to its original place in the inventory; same goes for chests. 

**To Reproduce** *(Steps to reproduce the behavior)*:
Try to use designated hotkeys to move items about in your inventory. 

**Time and Date** *(If applicable, add the time (in GMT+1) and date (DD.MM.YYYY) of the issue)*:
05/18/2020 ; 05/31/2020

**Screenshots/Videos (Delete if not needed)** *(If applicable, add screenshots/videos to help explain your problem)*:
https://www.youtube.com/watch?v=X5N9qdNQcDk&feature=youtu.be
https://www.youtube.com/watch?v=nsGcFYSns64&feature=youtu.be

**Additional context (Delete if this isn't needed)** *(Add any other context about the problem here)*:
Could be due to the plugin preventing Shulkerboxes from going into enderchests, but not known for certain.

**Comment by FrozenBeard** [comment]
Fixed on July 25th 2020
https://discordapp.com/channels/139382225375330305/545688946143657985/736538223286943805

It was the Admin Shop plugin blocking hotkeys.
