### ISSUE TITLE
Change [COMP] BOTM missive message to September

### ISSUE THREAD

**Issue by Markusi13** [PirateCraft/dev#2]
**Describe the bug** *(A clear and concise description of what the bug is)*:
The [COMP] Missive says "Enter July 2020 Build of the Month Competition" and the link is still for the june botm.

**To Reproduce** *(Steps to reproduce the behavior)*:
Be online and wait for missive to pop up.

**Expected behavior** *(A clear and concise description of what you expected to happen)*:
The message and the link should be changed to september

**Screenshots (Delete if not needed)** *(If applicable, add screenshots to help explain your problem)*:
![Screenshot](https://user-images.githubusercontent.com/13572005/89944690-849a7280-dc20-11ea-8aac-ef4dd2c9a4ed.png)

**Comment by FrozenBeard** [comment]
Fixed.
