### ISSUE TITLE
For all players, Buttons/Levers aren't working to open doors forcing us to use /doors to open them. (ILoveLegq)

### ISSUE THREAD

**Issue by CreatingWithKass** [PirateCraft/dev#20]
**Describe the bug** *(A clear and concise description of what the bug is)*:
For all players, Buttons/Levers aren't working to open doors forcing us to use /doors to open them. We've tried copying the set ups gods uses in cove and everything but the power block isn't reacting with the redstone.

**To Reproduce** *(Steps to reproduce the behavior)*:
Create a door and try to use redstone to activate the power block. If you know about /doors and /bdm, then this should be something you're able to do; otherwise the bug doesn't apply. It supposedly does not function correctly from there and the player is forced to use /doors instead. 

**Time and Date** *(If applicable, add the time (in GMT+1) and date (DD.MM.YYYY) of the issue)*:
07/24/2020

**Screenshots/Videos (Delete if not needed)** *(If applicable, add screenshots/videos to help explain your problem)*:
![glitcheddoors](https://user-images.githubusercontent.com/69595267/90287800-91001480-de46-11ea-8579-cbb4a6e06ae8.png)

**Additional context (Delete if this isn't needed)** *(Add any other context about the problem here)*:
@Happy Pills snap, can't figure this out, @LEGQ said another perm may be needed
If it is it's an easy fix
If not I'll talk to the devs' - GodsDead's response; however it is being posted because the issue remains unresolved.

**Comment by FrozenBeard** [comment]
Redstone for `/doors` was fixed July 31st 2020.
Changelog:
https://discordapp.com/channels/139382225375330305/545688946143657985/738691918703362129

Use /doorinfo to find where to place your power block (Center).
