### ISSUE TITLE
All wool and terracotta will not show on a normal map unless there is a block underneath them. (Fabul0usGandalf)

### ISSUE THREAD

**Issue by CreatingWithKass** [PirateCraft/dev#21]
**Describe the bug** *(A clear and concise description of what the bug is)*:
All wool and all terracotta colors (maybe even more types of blocks) are invisible if there isn't a block directly under them.  If there is a block directly under them the wool/terracotta is shown normally on the map. This applies to all chunks. 

**To Reproduce** *(Steps to reproduce the behavior)*:
Place wool or terracotta at least one block above the ground with nothing beneath it. Then use a blank map to show the area; the wool or terracotta will not show on the map. If you then place blocks beneath the wool/terracotta and use another new map, it will then show without problem. 

**Time and Date** *(If applicable, add the time (in GMT+1) and date (DD.MM.YYYY) of the issue)*:
07/24/2020

**Screenshots/Videos (Delete if not needed)** *(If applicable, add screenshots/videos to help explain your problem)*:
![visiblebug](https://user-images.githubusercontent.com/69595267/90288182-5480e880-de47-11ea-9503-5c9b9a60629d.png)
![visiblebug2](https://user-images.githubusercontent.com/69595267/90288183-55b21580-de47-11ea-801b-99c868d415fc.png)

**Additional context (Delete if this isn't needed)** *(Add any other context about the problem here)*:
These are the only blocks that have been confirmed to glitch in this way; there might be more.

**Comment by FrozenBeard** [comment]
Well this is unique, we don't have anything that changes maps, but are you using a client above 1.12.2? 
I bet this is a report from a newer client.
