### ISSUE TITLE
Submarines are still broken. They do not function when you meet all of the requirements, and players have to add unnecessary blocks.

### ISSUE THREAD

**Issue by CreatingWithKass** [PirateCraft/dev#22]
**Describe the bug** *(A clear and concise description of what the bug is)*:
Stained glass blocks aren't being counted for the 50% required blocks on submarines. I only tested with black stained glass, not sure if other colors work but regular glass does work. 
I got a sub to work by ripping out all the interior and replacing it with wool so the ship is 50% wool but that's not supposed to be like that, so the submarines do not follow the listed requirements. 

**To Reproduce** *(Steps to reproduce the behavior)*:
Create a submarine following the steps listed in /ships; it might require far more wool to be functional, and not allow you to use stained glass for the glass requirement, only normal glass. 

**Time and Date** *(If applicable, add the time (in GMT+1) and date (DD.MM.YYYY) of the issue)*:
07/13/2020

**Comment by FrozenBeard** [comment]
Both ids 160 # White Stained Glass Pane (minecraft:stained_glass_pane) and 95 # Stained Glass (minecraft:stained_glass) are on Barracuda, Seawolf and Submarine were in the blocks allowed, but only 160 was on in the flyblocks (Blocks required for sailing)

I have added block 95 to flyblocks for all 3 subs.
