### ISSUE TITLE
The message for the Discord link still says they get 20$... shouldn't this be changed? (PIPPIP5789)

### ISSUE THREAD

**Issue by CreatingWithKass** [PirateCraft/dev#23]
**Describe the bug** *(A clear and concise description of what the bug is)*:
When someone links and verifies their Discord to the server's Discord, it still gives the $20 gained announcement in-game. Shouldn't this be removed?

**To Reproduce** *(Steps to reproduce the behavior)*:
Using /discord in-game, a player links their discord through PMC chat and it announces that they have earned $20, though that was thought to have been removed. 

**Time and Date** *(If applicable, add the time (in GMT+1) and date (DD.MM.YYYY) of the issue)*:
07/13/2020

**Comment by FrozenBeard** [comment]
Fixed.
