### ISSUE TITLE
PVP Can't land critical hits on players while using Strength III potion

### ISSUE THREAD

**Issue by CrazyMoneyy** [PirateCraft/dev#24]
**Describe the bug** *(A clear and concise description of what the bug is)*:
Using Strength III Potion you can't land a critical hit on a player. It will register as a normal hit.

**To Reproduce** *(Steps to reproduce the behavior)*:
Drink Viking War Brew > Get a test person to land your critical hits. > You don't see the ''crit hit particals'' as well as the sound of it.

**Time and Date** *(If applicable, add the time (in GMT+1) and date (DD.MM.YYYY) of the issue)*:
22:05, 14 August 2020

**Screenshots/Videos (Delete if not needed)** *(If applicable, add screenshots/videos to help explain your problem)*:
https://we.tl/t-jAdm6tCg5F WETransfer Link (sorry for the laggy video my laptop aint best :I) 

**Additional context (Delete if this isn't needed)** *(Add any other context about the problem here)*:
Critting a person doesnt work with the strength III, but this might also be effected because of the blindness I've got with the potion as well. I dont have normal blindness potions so I cant test that. Could be both factors

**Comment by FrozenBeard** [comment]
I'm going to assume Strength III potions are not legit in Minecraft as you are using a custom brew and that you can only use Strength II crafting normally right? Which means as this custom brew has been created outside the boundaries of the main game whatever is blocking it (Most likely AC) there is no way on earth any custom exceptions will be added by the developer, things like this brew need to just stop being added.
@Thefroness is this item "Viking War Brew" from an event?
