### ISSUE TITLE
/bounty list numbers of bounty's are messed up, goes from 5 - 6 - 7 and jumps from 7 to 16, the numbers don't line up.

### ISSUE THREAD

**Issue by CrazyMoneyy** [PirateCraft/dev#26]
**Describe the bug** *(A clear and concise description of what the bug is)*:
Small bug about the the numbers from /bounty list 1 and /bounty list 2 lining up. The numbers of bounty's there are at that moment go from 1 - 2 - 3 - 4 - 5 - 6 - 7 - 16 - 17 - 18 etc. It makes jump from 7 to 16. After that at /bounty list 2 the numbers jump from 16 to 18, 18 to 20, 20 to 22. 

**To Reproduce** *(Steps to reproduce the behavior)*:
Type in chat /bounty list 1 and also /bounty list 2. There must be atleast like 8 or 9 people with a bounty online for this to work.

**Time and Date** *(If applicable, add the time (in GMT+1) and date (DD.MM.YYYY) of the issue)*:
23:40 14 August 2020

**Comment by FrozenBeard** [comment]
@iwanio for reference for the new version.

This is something I had also noticed over the years.
