### ISSUE TITLE
If you do /spawn as captain there is the 5 second timer but with /warp spawn it's instant. 

### ISSUE THREAD

**Issue by CreatingWithKass** [PirateCraft/dev#27]
**Describe the bug** *(A clear and concise description of what the bug is)*:
When a captain contributor does /warp spawn, they instantly TP to spawn without a 5 second timer. But when they type /spawn they have to wait the 5 seconds that non-donors have to wait through. 

**To Reproduce** *(Steps to reproduce the behavior)*:
If you're captain rank, try /warp spawn; the teleportation is instant. Then try /spawn, you will have to wait 5 seconds before teleported. 

**Time and Date** *(If applicable, add the time (in GMT+1) and date (DD.MM.YYYY) of the issue)*:
8/15/2020 ; 8:28 PM GMT+1

**Comment by FrozenBeard** [comment]
Added permission that should bypass warmup, no help to anyone online when I asked captains to try the new spawn yesterday. Why cant people help for legit 5 seconds.
