### ISSUE TITLE
Chat emoticon :omg: doesnt work, changes to :shiver me timbers:

### ISSUE THREAD

**Issue by CrazyMoneyy** [PirateCraft/dev#29]
**Describe the bug** *(A clear and concise description of what the bug is)*:
The chat emoji :omg: doesnt work due to normal ''omg'' always changing to Shiver me timbers since that is a thing.

**To Reproduce** *(Steps to reproduce the behavior)*:
Type in chat :omg: there should come this emoji but it turns out to :shiver me timbers:
![image](https://user-images.githubusercontent.com/69697407/90390633-f85ad600-e08b-11ea-91fa-5d32814abacc.png) 

**Time and Date** *(If applicable, add the time (in GMT+1) and date (DD.MM.YYYY) of the issue)*:
12.18 17 August 2020

**Screenshots/Videos (Delete if not needed)** *(If applicable, add screenshots/videos to help explain your problem)*:
![image](https://user-images.githubusercontent.com/69697407/90390553-d3666300-e08b-11ea-9c50-1c0b513e1c48.png)

**Comment by TomLewis** [comment]
Ha, yeah! silly me.

Either we can remove "omg" being changed, or change the :omg:
