### ISSUE TITLE
Snowballs, eggs, and other types of hand-thrown projectiles, no longer tag a player.

### ISSUE THREAD

**Issue by Markusi13** [PirateCraft/dev#3]
**Describe the bug** *(A clear and concise description of what the bug is)*:
Throwing snowballs, eggs, and other types of hand-thrown projectiles, no longer tag a player.

**To Reproduce** *(Steps to reproduce the behavior)*:
Shoot either projectile at a player in a pvp zone.

**Time and Date** *(If applicable, add the time and date of the issue)*:
11.08.2020 | 21:55 GMT+1

**Comment by FrozenBeard** [comment]
Not a bug, a setting as they are "No Damage Hits" which means they don't actually do damage, people only use this to prevent people from teleporting.
Re-enabled.
