### ISSUE TITLE
After changing crew description it says ''your clan''

### ISSUE THREAD

**Issue by CrazyMoneyy** [PirateCraft/dev#31]
**Describe the bug** *(A clear and concise description of what the bug is)*:
Small fault/bug; After changing the description of your crew it says ''You have succesfully changed your clans's description'' While this should be ''your crew's''

**To Reproduce** *(Steps to reproduce the behavior)*:
Type /crew description [anything] and press enter you get that message.

**Time and Date** *(If applicable, add the time (in GMT+1) and date (DD.MM.YYYY) of the issue)*:
14:52 17 August 2020

**Screenshots/Videos (Delete if not needed)** *(If applicable, add screenshots/videos to help explain your problem)*:
![image](https://user-images.githubusercontent.com/69697407/90398200-5510bd80-e099-11ea-8a9e-c5127dfbe3c8.png)

**Comment by TomLewis** [comment]
Fixed in https://discordapp.com/channels/139382225375330305/545688946143657985/745752014566195230
