### ISSUE TITLE
Putting ''!'' in front of your msg to talk cross server doesnt work.

### ISSUE THREAD

**Issue by CrazyMoneyy** [PirateCraft/dev#34]
**Describe the bug** *(A clear and concise description of what the bug is)*:
Talking from creative to survival or other way around using a ! in front of your msg also broke as well as the /msg cross server. You can't talk across the server with it anymore. /msg not working is already an issue made

**To Reproduce** *(Steps to reproduce the behavior)*:
Have 2 persons in different servers and talk using ! in front of the message. See if you can see the other person his message. 

**Time and Date** *(If applicable, add the time (in GMT+1) and date (DD.MM.YYYY) of the issue)*:
21:58 18 August 2020

#10 < Earlier Issue from the across server /msg

**Comment by TomLewis** [comment]
Fixed a while ago.
