### ISSUE TITLE
VoteCrate does not give EXP anymore; shows it as a winning prize, but gives the player nothing. 

### ISSUE THREAD

**Issue by CreatingWithKass** [PirateCraft/dev#37]
**Describe the bug** *(A clear and concise description of what the bug is)*:
When a player uses a VoteCrate key and gets EXP bottles as a prize, the EXP won does not go into the player's EXP bar. This leaves the player using a key but getting no prize, as it "confirms" the win but does not give the EXP. 

**To Reproduce** *(Steps to reproduce the behavior)*:
Vote using /vote, and then use the keys at /warp cove. If EXP is won as a prize, it might not add the EXP to the EXP bar even though it confirms the win. 

**Time and Date** *(If applicable, add the time (in GMT+1) and date (DD.MM.YYYY) of the issue)*:
8/22/2020 ; 3:09 P.M. GM+1

**Screenshots/Videos (Delete if not needed)** *(If applicable, add screenshots/videos to help explain your problem)*:
https://www.youtube.com/watch?v=MG5z6dqWsrI&feature=youtu.be
![glitchxp2](https://user-images.githubusercontent.com/69595267/90961236-7563c200-e475-11ea-9ba1-5c66e751fc6f.png)
![glitchxp](https://user-images.githubusercontent.com/69595267/90961237-75fc5880-e475-11ea-9735-88b075877c32.png)

**Comment by TomLewis** [comment]
Fixed.
