### ISSUE TITLE
Spam placing sponges in water in someone elses claim drains their water

### ISSUE THREAD

**Issue by Markusi13** [PirateCraft/dev#4]
**Describe the bug** *(A clear and concise description of what the bug is)*:
You can drain water in other people's claims without trust using sponge and spam placing it.

**To Reproduce** *(Steps to reproduce the behavior)*:
Spam place sponges in water in a claim you don't own/have trust in.

**Time and Date** *(If applicable, add the time (in GMT+1) and date (DD.MM.YYYY) of the issue)*:
11.08.2020 | 22:18

**Screenshots/Videos (Delete if not needed)** *(If applicable, add screenshots/videos to help explain your problem)*:
![2020-08-11_23 15 29](https://user-images.githubusercontent.com/13572005/89950004-09898a00-dc29-11ea-9224-480af6ea8227.png)

**Additional context (Delete if this isn't needed)** *(Add any other context about the problem here)*:
It doesn't always instantly occure, took me quite some time to get it to work.

**Comment by FrozenBeard** [comment]
Fixed! It was the redstone sponge system that overrode normal sponge use, I have disabled redstone sponges.
