### ISSUE TITLE
'Quartermaster' is spelled wrong in this Missive message. 

### ISSUE THREAD

**Issue by CreatingWithKass** [PirateCraft/dev#40]
**Describe the bug** *(A clear and concise description of what the bug is)*:
Quartermaster is spelled 'Quatermaster' in the donation missive message. 

**To Reproduce** *(Steps to reproduce the behavior)*:
Pay attention to messages sent by the server. It'll make its round, and quartermaster will be misspelled. 

**Time and Date** *(If applicable, add the time (in GMT+1) and date (DD.MM.YYYY) of the issue)*:
08/27/2020

**Screenshots/Videos (Delete if not needed)** *(If applicable, add screenshots/videos to help explain your problem)*:
![typo](https://user-images.githubusercontent.com/69595267/92400099-531aa700-f0f9-11ea-91f3-c87ca6e1825c.png)

**Comment by TomLewis** [comment]
Fixed for next push.
