### ISSUE TITLE
The automatic mail sent after donating (or when losing donation perks) uses the old mail system.

### ISSUE THREAD

**Issue by CreatingWithKass** [PirateCraft/dev#41]
**Describe the bug** *(A clear and concise description of what the bug is)*:
The automatic messages sent to players after donating or losing their donation perks still goes by the old mail system. 

**To Reproduce** *(Steps to reproduce the behavior)*:
Only possible if you've donated; pay attention to the /mail sent to you by the server. It should be stuck with the old mail system, not the updated one. 

**Time and Date** *(If applicable, add the time (in GMT+1) and date (DD.MM.YYYY) of the issue)*:
09/02/2020

**Comment by TomLewis** [comment]
Changed on all shop items.
