### ISSUE TITLE
'Permanent' is misspelled

### ISSUE THREAD

**Issue by CreatingWithKass** [PirateCraft/dev#42]
**Describe the bug** *(A clear and concise description of what the bug is)*:
'Permanent' is spelled 'perminant' on PirateCraft's website, above the section talking about purchasing permanent parrots. 

**To Reproduce** *(Steps to reproduce the behavior)*:
Go to PMC's website and navigate to where the parrots are purchasable. At the top of the page it is misspelled. 

**Time and Date** *(If applicable, add the time (in GMT+1) and date (DD.MM.YYYY) of the issue)*:
09/07/2020 4:49 A.M. GMT+1
**Screenshots/Videos (Delete if not needed)** *(If applicable, add screenshots/videos to help explain your problem)*:
![typo](https://user-images.githubusercontent.com/69595267/92402048-ebfef180-f0fc-11ea-948c-ca0da2d50f1e.png)

**Comment by TomLewis** [comment]
Fixed.
