### ISSUE TITLE
The gold marker blocks when claiming are sometimes physical enough for a player to stand on, which results in them getting kicked or injured if in water.

### ISSUE THREAD

**Issue by CreatingWithKass** [PirateCraft/dev#44]
**Describe the bug** *(A clear and concise description of what the bug is)*:
When claiming or showing a claim's borders, gold blocks are used to mark the corners. When showing a claim in water, the player can sometimes stand on these corners, and it causes the player to then get kicked for 'Jesus Hacks' by the server's anti-cheat. Does not happen every single time, but randomly. 
Sometimes it damages the player instead of kicking them, which is just as odd. 

**To Reproduce** *(Steps to reproduce the behavior)*:
Create a claim in a body of water, and then try to stand on the gold block borders. It will most likely either injure the player or kick them for "Jesus Hacks". 

**Time and Date** *(If applicable, add the time (in GMT+1) and date (DD.MM.YYYY) of the issue)*:
09/07/2020 2:25 P.M. GMT+1 

**Screenshots/Videos (Delete if not needed)** *(If applicable, add screenshots/videos to help explain your problem)*:
https://youtu.be/YjQPEpuYOn4

**Comment by TomLewis** [comment]
Very, very old bug, known & reported many years ago, GP wont fix.
