### ISSUE TITLE
Falsely kicked for 'aura' when spam killing skeletons at /warp spawner. 

### ISSUE THREAD

**Issue by CreatingWithKass** [PirateCraft/dev#45]
**Describe the bug** *(A clear and concise description of what the bug is)*:
Some players are falsely kicked for using an 'aura' when spam-killing skeletons at /warp spawner. 

**To Reproduce** *(Steps to reproduce the behavior)*:
Quickly kill skeletons at /warp spawner. Sometimes the server will glitch and the player will be falsely kicked for using an aura. 

**Time and Date** *(If applicable, add the time (in GMT+1) and date (DD.MM.YYYY) of the issue)*:
09/07/2020 2:48 P.M. GMT+1

**Comment by TomLewis** [comment]
Specifically test with tools/armour that people are using when they are kicked. It will be something to do with specific enchants.

**Comment by Mrlimethewise** [comment]
fixed
