### ISSUE TITLE
'Introductions' is misspelled on PirateCraft's Website

### ISSUE THREAD

**Issue by CreatingWithKass** [PirateCraft/dev#46]
**Describe the bug** *(A clear and concise description of what the bug is)*:
On the drop-down menu for PirateCraft's website, 'introductions' is spelled like 'Intoroductions' 

**To Reproduce** *(Steps to reproduce the behavior)*:
Navigate to the PirateCraft website and go to the drop-down menu at the top. On the left side of the screen, introductions is spelled intoroductions. 

**Time and Date** *(If applicable, add the time (in GMT+1) and date (DD.MM.YYYY) of the issue)*:
09/07/2020 3:32 GMT+1

**Screenshots/Videos (Delete if not needed)** *(If applicable, add screenshots/videos to help explain your problem)*:
![typo](https://user-images.githubusercontent.com/69595267/92407506-c11a9a80-f108-11ea-82e3-e5f063cba6cd.png)

**Comment by TomLewis** [comment]
Thanks, Fixed locally for next push.
