### ISSUE TITLE
Vote Crates not working

### ISSUE THREAD

**Issue by IwanIDev** [PirateCraft/dev#47]
**Describe the bug** *(A clear and concise description of what the bug is)*:
Vote Crates not functioning for anybody. Appears to be mentioning a cooldown. 

**To Reproduce** *(Steps to reproduce the behavior)*:
Obtain a vote key, and attempt to use it on any of the vote crates around cove. No GUI will appear, and after a few attempts a cooldown message will show in chat.

**Time and Date** *(If applicable, add the time (in GMT+1) and date (DD.MM.YYYY) of the issue)*:
16:32, 10/09/2020

**Screenshots/Videos (Delete if not needed)** *(If applicable, add screenshots/videos to help explain your problem)*:
http://www.youtube.com/watch?v=Cc7iQQzOQ1E

**Comment by TomLewis** [comment]
Fixed sep 12th https://discordapp.com/channels/139382225375330305/545688946143657985/754128849926750290
