### ISSUE TITLE
Colour chats typing for staff do not work anymore on survival.

### ISSUE THREAD

**Issue by CrazyMoneyy** [PirateCraft/dev#48]
**Describe the bug** *(A clear and concise description of what the bug is)*:
Trying to type in chat using ''&cHey there!'' doesnt make the colored anymore. This is with all colour codes. Command /chc colour says we have no permission (see screenshot 1). When you try typing in chat with a colour code it gives a weird ''&'' symbol, normally it's different. (see screenshot 2)

**To Reproduce** *(Steps to reproduce the behavior)*:
Try typing in colour in chat as helper, mod or admin it doesn't work, nor does /chc colour.

**Time and Date** *(If applicable, add the time (in GMT+1) and date (DD.MM.YYYY) of the issue)*:
19.04 10 September 2020

**Screenshots/Videos (Delete if not needed)** *(If applicable, add screenshots/videos to help explain your problem)*:
![image](https://user-images.githubusercontent.com/69697407/92777943-fc36fb00-f3a0-11ea-9225-32b23aa32915.png)
![image](https://user-images.githubusercontent.com/69697407/92778360-618aec00-f3a1-11ea-9fa7-6360aa21fc82.png)

**Additional context (Delete if this isn't needed)** *(Add any other context about the problem here)*:
Side note: It still does work on creative I tested this with lazy she can still type coloured there, survival only.

**Comment by TomLewis** [comment]
I have added the new permissions for both GUI and using color in chat, but it seems ChatControl Pro has broken in-game chat colors even when given the correct permissions. 

https://github.com/kangarko/ChatControl-Pro/issues/1934
