### ISSUE TITLE
crew ranks with spaces cannot be removed

### ISSUE THREAD

**Issue by johenkel** [PirateCraft/dev#49]
**Describe the bug** *(A clear and concise description of what the bug is)*:
after creating a crew rank using the new gui ( rank that has a space in its name) , the rank cannot be removed anymore afterwards

**To Reproduce** *(Steps to reproduce the behavior)*:
use /crew rank delete name of rank - when "name of rank" is the actual rank
it will show no error message , rather just an info on how to use the command

**Time and Date** *(If applicable, add the time (in GMT+1) and date (DD.MM.YYYY) of the issue)*:
as of 09.09.2020 

**Screenshots/Videos (Delete if not needed)** *(If applicable, add screenshots/videos to help explain your problem)*:
Video 1 - https://mega.nz/file/6SRnVCTA#A-tWKKpaFpflMKWVCp_gyRsLhhLZU8IZGAnPwaacXTM 
Video 2 - https://mega.nz/file/GTAlFAiK#EZ9XKpuxw3ZXDPkvG09QKW0LRxXweNNz0_U5lA1iUY4

**Additional context (Delete if this isn't needed)** *(Add any other context about the problem here)*:
sent in by izzyfutbol

**Comment by TomLewis** [comment]
Already reported https://github.com/RoinujNosde/SimpleClans/issues/48 & should be fixed in next build of simpleclans.
