### ISSUE TITLE
Rightclicking stuff that you can open (like a wooden door/trapdoor) using an enderpeal doesn't open them

### ISSUE THREAD

**Issue by Markusi13** [PirateCraft/dev#5]
**Describe the bug** *(A clear and concise description of what the bug is)*:
When you rightclick stuff that you can open like a wooden door/trapdoor using an enderpearl, it won't actually open the door. If you spam rightclick the door, it even puts the enderpearl on cooldown.

**To Reproduce** *(Steps to reproduce the behavior)*:
Rightclick a wooden door/wooden trapdoor with a enderpearl.

**Time and Date** *(If applicable, add the time (in GMT+1) and date (DD.MM.YYYY) of the issue)*:
11.08.2020 | 22:30

**Additional context (Delete if this isn't needed)** *(Add any other context about the problem here)*:
Throwing enderpearls into claims you don't own/don't have trust in triggers the cooldown for the enderpearl.

**Comment by FrozenBeard** [comment]
Added wooden doors to ignored blocks for enderpearl cooldown plugin.

```
ignored-block-types:
  - "ENDER_CHEST"
  - "CHEST"
  - "CRAFTING_TABLE"
  - "ACACIA_DOOR"
  - "ACACIA_DOOR_ITEM"
  - "BIRCH_DOOR"
  - "BIRCH_DOOR_ITEM"
  - "DARK_OAK_DOOR"
  - "DARK_OAK_DOOR_ITEM"
  - "JUNGLE_DOOR"
  - "JUNGLE_DOOR_ITEM"
  - "JUNGLE_DOOR_ITEM"
  - "SPRUCE_DOOR"
  - "SPRUCE_DOOR_ITEM"
```
