### ISSUE TITLE
Blocks glitch and vanish from the large /bdm door at /warp shop8 randomly. 

### ISSUE THREAD

**Issue by CreatingWithKass** [PirateCraft/dev#50]
**Describe the bug** *(A clear and concise description of what the bug is)*:
Every now and then a few blocks seem to disappear from /warp shop8's large /bdm door. The distinctive row just disappears and reappears every now and then with seemingly no explanation. Players can walk in the spot of the missing blocks. 

**To Reproduce** *(Steps to reproduce the behavior)*:
Go to /warp shop8 and move to the front of the building. Mess with the door - sometimes the blocks will appear to be there, other times they won't be. The player can walk in the spot of the missing blocks as well. 

**Time and Date** *(If applicable, add the time (in GMT+1) and date (DD.MM.YYYY) of the issue)*:
9/11/2020 10:31 P.M. GM+1

**Screenshots/Videos (Delete if not needed)** *(If applicable, add screenshots/videos to help explain your problem)*:
![glitchydoor](https://user-images.githubusercontent.com/69595267/92980888-af692800-f465-11ea-8ebb-93c2daad09e3.png)

**Additional context (Delete if this isn't needed)** *(Add any other context about the problem here)*:
Messed around with the door. It was glitched like the image shows above, and when I activated the door again it fixed itself. Seems to reoccur every now and then without any rhyme or reason.

**Comment by TomLewis** [comment]
Client side.
