### ISSUE TITLE
These words/phrases seem to bypass the spam cooldown filter. 

### ISSUE THREAD

**Issue by CreatingWithKass** [PirateCraft/dev#51]
**Describe the bug** *(A clear and concise description of what the bug is)*:
Players are able to repeatedly use "wb" which turns into "welcome back" without a cooldown, as well as spam "k" and "ok" as fast as they want. It can flood the chat. The following images are not the players purposefully spamming in order to get punished, but instead testing the bug. 

**To Reproduce** *(Steps to reproduce the behavior)*:
Don't reproduce this - but repeatedly type "ok", "k", or "wb" in global chat. It'll allow the player to continue to type it quickly without getting the anti-spam cooldown. 

**Time and Date** *(If applicable, add the time (in GMT+1) and date (DD.MM.YYYY) of the issue)*:
9/04/2020 7:30 A.M. GM+1

**Screenshots/Videos (Delete if not needed)** *(If applicable, add screenshots/videos to help explain your problem)*:
![spam](https://user-images.githubusercontent.com/69595267/92981566-66ff3980-f468-11ea-9a01-336357ddcddf.png)
![spam2](https://user-images.githubusercontent.com/69595267/92981571-6a92c080-f468-11ea-9c05-3f2606839a8d.png)
![spam3](https://user-images.githubusercontent.com/69595267/92981575-6bc3ed80-f468-11ea-9ee8-55ca54b5aa5f.png)

**Comment by TomLewis** [comment]
These are whitelisted words, this is intended, otherwise people would get flagged for "spamming similar words" for basic speaking and replying to people.
Full set of whitelisted words:
```
    Whitelist_Similarity:
    - hello
    - hey
    - hi
    - welcome
    - ahoy
    - Welcome back
    - Welcome to
    - wb
    - ty
    - np
    - gratz
    - congrats
    - lol
    - LOL
    - haha
    - menu
    - true
    - false
    - lol
    - it
    - the
    - he
    - she
    - me
    - when
    - then
    - there
    - their
    - k
    - ok
```
