### ISSUE TITLE
The following crew commands do not work: /crew mostkilled, players with ally.add cannot see ally requests, leaders cannot promote new leaders, and no one can add or withdraw money from crew bank.

### ISSUE THREAD

**Issue by CreatingWithKass** [PirateCraft/dev#52]
**Describe the bug** *(A clear and concise description of what the bug is)*:
With the new crew update there are major aspects that do not seem to work, including: /crew mostkilled, leaders are unable to promote new leaders even when all the crew's leaders are online, those with ally.add permissions cannot see ally requests from outside crews, and no one (including leaders) can add or withdraw from their crew banks. 

**To Reproduce** *(Steps to reproduce the behavior)*:
Try doing any of the above commands if you are a crew leader. For most it seems to not be functional. 

**Time and Date** *(If applicable, add the time (in GMT+1) and date (DD.MM.YYYY) of the issue)*:
8/24/2020  9:46 P.M. GM+1

**Comment by Mrlimethewise** [comment]
working in 1.18 so far
