### ISSUE TITLE
Mending does not work on the Creative server. It can be dragged into the inventory and then disappears. 

### ISSUE THREAD

**Issue by CreatingWithKass** [PirateCraft/dev#53]
**Describe the bug** *(A clear and concise description of what the bug is)*:
When on /creative (/server creative), the player can grab a mending enchantment book and drag it into their inventory - but then the enchantment word "mending" disappears and the book becomes useless. When tested on armor or weapons, the player cannot add the broken book to anything. 

**To Reproduce** *(Steps to reproduce the behavior)*:
On /creative, drag a mending book into your inventory. The word 'mending' will disappear from the book, and cannot be used on any tools or armor. 

**Time and Date** *(If applicable, add the time (in GMT+1) and date (DD.MM.YYYY) of the issue)*:
8/23/2020 2:16 A.M. GM+1

**Screenshots/Videos (Delete if not needed)** *(If applicable, add screenshots/videos to help explain your problem)*:
https://youtu.be/ukAH3yRuKHE

**Comment by TomLewis** [comment]
What about other enchants?

**Comment by CreatingWithKass** [comment]
> What about other enchants?

Seems to work with other enchants, just not mending.

**Comment by Mrlimethewise** [comment]
tested this before server update seemed to be fixed
