### ISSUE TITLE
Crew leaders are unable to delete ranks that have spaces in the name. 

### ISSUE THREAD

**Issue by CreatingWithKass** [PirateCraft/dev#55]
**Describe the bug** *(A clear and concise description of what the bug is)*:
When a crew leader does /crew and goes through the steps to delete a rank with spaces in it, the server does not recognize the ability to delete that rank. It also happens when the player does /crew rank delete rather than /crew.

**To Reproduce** *(Steps to reproduce the behavior)*:
Go through the steps outlined in the video below. Use the command /crew, click on the green banner, select the rank you wish to delete, and attempt. It will most likely not work. Another way to test is to try to /crew rank delete method, which seems to fail as well. 

**Time and Date** *(If applicable, add the time (in GMT+1) and date (DD.MM.YYYY) of the issue)*:
08/19/2020 6:57 P.M. GM+1

**Screenshots/Videos (Delete if not needed)** *(If applicable, add screenshots/videos to help explain your problem)*:
https://youtu.be/clNqsYuifec

**Comment by TomLewis** [comment]
Dupe.

This is the third time this has been reported.
#49 In this repo.
Which I already posted in https://github.com/RoinujNosde/SimpleClans/issues/48

Closed.
