### ISSUE TITLE
Players randomly die when doing /spawn with seemingly no reason. 

### ISSUE THREAD

**Issue by CreatingWithKass** [PirateCraft/dev#56]
**Describe the bug** *(A clear and concise description of what the bug is)*:
A few players have reported dying instantly when they do /spawn. There is no obvious reason for the deaths, as it has happened to multiple people with different ranks and different pings at varying times. 

**To Reproduce** *(Steps to reproduce the behavior)*:
Try /spawn multiple times under different circumstances (varying pings, locations) and explain what happened in as much detail as possible if death occurs. Take a screenshot of the death message if there is one, as well as time and ping. 

**Time and Date** *(If applicable, add the time (in GMT+1) and date (DD.MM.YYYY) of the issue)*:
09/09/2020 4:18 A.M. GM+1 

**Additional context (Delete if this isn't needed)** *(Add any other context about the problem here)*:
We are still trying to collect more information, as most is unknown about this bug. Could have something to do with a mix of a player having high ping and spawning on a block without blocks beneath it. Standby for further updates.

**Comment by TomLewis** [comment]
Needs more info and how to reproduce.
For example if this is just for certain ranks, do certain ranks have a custom spawn still?

**Comment by CreatingWithKass** [comment]
> Needs more info and how to reproduce.
> For example if this is just for certain ranks, do certain ranks have a custom spawn still?

It seems to happen randomly to any rank member. Mr_Mistery12 is our newest case, a gunner. He /spawn while underground and it killed him - said that when he landed in spawn it seemed fine at first and then he suddenly died. His death message was "Mr_Mistery12 failed to stay alive". 
I had him go back to where he was and test it again, so warping while underground. He survived this time, so it doesn't seem to matter where the player is when they TP.

**Comment by TomLewis** [comment]
- Removed carpet, keep this ticket open incase it happens again.

**Comment by CreatingWithKass** [comment]
The beast has returned... today a deckie joined the server for the first time, and then instantly died right after. They quit before I was able to question them. 
![glitch](https://user-images.githubusercontent.com/69595267/95000166-80d5fd00-058c-11eb-9cc2-841d71b4c2dd.png)

**Comment by TomLewis** [comment]
But how!
