### ISSUE TITLE
Rankup for Firstmate says travel 5,000,000 block instead of 500,000 on PMC's website. 

### ISSUE THREAD

**Issue by CreatingWithKass** [PirateCraft/dev#57]
**Describe the bug** *(A clear and concise description of what the bug is)*:
When ranking up to firstmate, a player must travel 500,000 blocks on foot. On the PMC website, it mistakenly says travel 5,000,000 blocks instead. 

**To Reproduce** *(Steps to reproduce the behavior)*:
Check the rankup requirements section of the website. It'll say 5,000,000 instead of 500,000. 

**Time and Date** *(If applicable, add the time (in GMT+1) and date (DD.MM.YYYY) of the issue)*:
9/15/2020 8:42 P.M. GM+1

**Screenshots/Videos (Delete if not needed)** *(If applicable, add screenshots/videos to help explain your problem)*:
![typooo](https://user-images.githubusercontent.com/69595267/93369647-aee1e000-f81d-11ea-9c28-92ad27a78b44.png)

**Comment by TomLewis** [comment]
Everything on that rank page is outdated, I need to start it from scratch.
