### ISSUE TITLE
/bdm door glitch: blocks disappearing again except this time the player must manually fix it. 

### ISSUE THREAD

**Issue by CreatingWithKass** [PirateCraft/dev#58]
**Describe the bug** *(A clear and concise description of what the bug is)*:
When using a /bdm door, some players experience a glitch where a section of the door does not move with the rest. This is like the other glitch, except the blocks don't disappear - they simply do not move. The owner of the door then has to rearrange the blocks to fix the glitch. Happens randomly, without cause or obvious reason. 

**To Reproduce** *(Steps to reproduce the behavior)*:
Mess with /bdm doors. Sometimes the doors will "break" and the owner will have to re-place sections to fix it. 

**Time and Date** *(If applicable, add the time (in GMT+1) and date (DD.MM.YYYY) of the issue)*:
9/17/2020 1:10 A.M. GM+1

**Additional context (Delete if this isn't needed)** *(Add any other context about the problem here)*:
I'll continue to test with my own /bdm doors, but it seems that this glitch is random and not too common.

**Comment by TomLewis** [comment]
Any chance there is a Brewing barrel in the same chunk? (can be any vertical space)

**Comment by CreatingWithKass** [comment]
> Any chance there is a Brewing barrel in the same chunk? (can be any vertical space)

I'll get back to you with this answer soon

**Comment by CreatingWithKass** [comment]
> Any chance there is a Brewing barrel in the same chunk? (can be any vertical space)

Alright, talked to Mystic (reporter of bug) and he said there is no brewing barrel in the area.

**Comment by TomLewis** [comment]
Without a way to reproduce, I cant submit it as its so vague! I will leave this ticket open, but until someone can figure out how to reproduce it each time, nout can be done!

**Comment by Mrlimethewise** [comment]
fixed in update
