### ISSUE TITLE
Sometimes when replying to people using /r you'll get an error message

### ISSUE THREAD

**Issue by Markusi13** [PirateCraft/dev#6]
**Describe the bug** *(A clear and concise description of what the bug is)*:
Sometimes when replying to people using /r, even if you had just used it moments ago, youll get an error message like
`[15:22:14] [main/INFO]: [CHAT] ! You have no one to whom you can reply.`
even though me (cysteen) and the player i was conversing with had used /r to reply to eachother perfectly fine.

**To Reproduce** *(Steps to reproduce the behavior)*:
Use /r to respond to a message you recieved via /msg or /r. 

**Time and Date** *(If applicable, add the time (in GMT+1) and date (DD.MM.YYYY) of the issue)*:
n/a

**Additional context (Delete if this isn't needed)** *(Add any other context about the problem here)*:
This bug was submitted by Cysteen and i couldn't confirm it myself.

**Comment by FrozenBeard** [comment]
Find a way to reproduce it, otherwise it cant be "fixed.
