### ISSUE TITLE
Missive says the server only supports from 1.12.2 - 1.15.2. 

### ISSUE THREAD

**Issue by CreatingWithKass** [PirateCraft/dev#60]
**Describe the bug** *(A clear and concise description of what the bug is)*:
The server's Missive messages says the server supports 1.12.2-1.15.2 clients, when the server actually supports up to the newer versions (1.16.2 or .3, I'm not sure).

**To Reproduce** *(Steps to reproduce the behavior)*:
Watch for the reoccurring Missive message in-game, it's bound to pop up. 

**Time and Date** *(If applicable, add the time (in GMT+1) and date (DD.MM.YYYY) of the issue)*:
9/19/2020 8:37 P.M. GM+1

**Screenshots/Videos (Delete if not needed)** *(If applicable, add screenshots/videos to help explain your problem)*:
![bugg](https://user-images.githubusercontent.com/69595267/93804669-a5d58200-fc14-11ea-9283-1464d024e81d.png)

**Comment by TomLewis** [comment]
Done!
