### ISSUE TITLE
The Summer Crate 2020 has been removed, but the floating tag above it is still there. 

### ISSUE THREAD

**Issue by CreatingWithKass** [PirateCraft/dev#61]
**Describe the bug** *(A clear and concise description of what the bug is)*:
When the shulker box for the Summer Crate 2020 keys was removed, the tag floating above the shulker remained even though the event is over. 

**To Reproduce** *(Steps to reproduce the behavior)*:
Go to /warp cove and go to where the crates (vote, head, etc) are. Where the 2020 crate used to be there is a floating tag that needs to be removed. 

**Time and Date** *(If applicable, add the time (in GMT+1) and date (DD.MM.YYYY) of the issue)*:
9/19/2020 10:33 P.M. GMT+1

**Screenshots/Videos (Delete if not needed)** *(If applicable, add screenshots/videos to help explain your problem)*:
![AHHH2](https://user-images.githubusercontent.com/69595267/93806636-6fe5cd00-fc17-11ea-90c7-6f4834773467.png)

**Comment by TomLewis** [comment]
Removed
