### ISSUE TITLE
[Restricted] signs are able to be used by players, but when they're made they get a "You do not have permission!" message. The sign still works, so the question is: are restricted signs not supposed to work, or is the message wrong? (Nick_A_Naut)

### ISSUE THREAD

**Issue by CreatingWithKass** [PirateCraft/dev#62]
**Describe the bug** *(A clear and concise description of what the bug is)*:
So there's a way to make sign shops 'Restricted', and you can whitelist certain permission groups (firstmate, captain, privateer etc.). However when you try to make a restricted sign, you are given a "You don't have permission to create this sign!" message, but when you actually make the sign it works fine. Is the error message incorrect, or are these signs not meant to be used by players? (Nick_A_Naut from #bugs) 

**To Reproduce** *(Steps to reproduce the behavior)*:
Create a [Restricted] sign. An error message will pop up when the player finishes making the sign, but it will work fine anyway. Check SignShops plugin for more information on how to create the sign. 

**Time and Date** *(If applicable, add the time (in GMT+1) and date (DD.MM.YYYY) of the issue)*:
9/23/2020 6:48 PM GMT+1 

**Screenshots/Videos (Delete if not needed)** *(If applicable, add screenshots/videos to help explain your problem)*:
![bug1](https://user-images.githubusercontent.com/69595267/94053899-e6fe9b00-fda8-11ea-9667-e49b8790b8ba.png)

**Additional context (Delete if this isn't needed)** *(Add any other context about the problem here)*:
A few more signs have this issue, so far the only other one found has been the [Share] sign.

**Comment by TomLewis** [comment]
Its just default permission given, so unless explicitly banned or removed via plugin or permissions.

Why, is this a problem having this sign? This has always been available.

**Comment by CreatingWithKass** [comment]
> Its just default permission given, so unless explicitly banned or removed via plugin or permissions.
> 
> Why, is this a problem having this sign? This has always been available.

The issue people are point out is it says they don't have permission even though they do. Since you have confirmed that this is a sign people are allowed to use, then the "You dont have permission to create this sign!" message is the 'bug' here. Simply just an incorrect message

**Comment by TomLewis** [comment]
Ive never used the sign, this is obviously someone thats looked up the plugin and tested out all the signs to see what they can use, at what point would this sign be useful to a player that its worth putting in the effort? nobodys used this sign in 8+ years
