### ISSUE TITLE
Poker Game Bugs: Players can't leave a game of poker if they don't /leave before the owner closes the game, and if two players get the same cards at the end of the game there's infinitely the ringing sound that can only be fixed when the player relogs.

### ISSUE THREAD

**Issue by CreatingWithKass** [PirateCraft/dev#65]
**Describe the bug** *(A clear and concise description of what the bug is)*:
Issue 1: If you don't /table leave before the host closes the table, the player gets an error trying to. The player is then stuck at the table and can't move more than 30 blocks away. (Capt_Lugnut reported) 
Issue 2: At the end of the game, if both players have the same cards (for example, Mindmeld and Khanye both ended the game with full house pair of 7s), the game will bug and constantly play the end ringing sound that will not stop unless the player relogs. (Mindmeld reported)

**To Reproduce** *(Steps to reproduce the behavior)*:
Play a game of poker. Wait until the host closes the game, and then try to /leave. The player will be trapped at the table and cannot go more than 30 blocks in any direction. 
Play a game of poker. If the players end up with the same hand by the end of the game, the end ringing tune will sound infinitely until the player relogs. 

**Time and Date** *(If applicable, add the time (in GMT+1) and date (DD.MM.YYYY) of the issue)*:
9/27/2020 9:36 P.M. GMT+1

**Comment by TomLewis** [comment]
Another bug, is that the owner of the table has to start the game.
This means that we cant just have a table people can join & play, the owner has to be online to start the game.

We cant give people permission to make tables either, as it involves teleporting people, could be used like a warp.
