### ISSUE TITLE
/bdm doors delete shulker boxes (Nick_A_Naut) 

### ISSUE THREAD

**Issue by CreatingWithKass** [PirateCraft/dev#66]
**Describe the bug** *(A clear and concise description of what the bug is)*:
It seems big doors ignore shulker boxes, and if one is in the way it just replaces the shulker box with the door. It deleted a player's shulker box (which was in the way of the opening door) and replaced it with a log.  

**To Reproduce** *(Steps to reproduce the behavior)*:
Place a shulker in the way of a /bdm door's opening. When the door opens and hits the block, it should cause the shulker to turn into a log and the player to lose the shulker and everything inside of it. 

**Time and Date** *(If applicable, add the time (in GMT+1) and date (DD.MM.YYYY) of the issue)*:
9/30/2020 3:15 P.M. GMT+1 

**Additional context (Delete if this isn't needed)** *(Add any other context about the problem here)*:
Will need additional testing by a staff member who has access to multiple shulker boxes. Not sure if the same occurs on /test or /creative, so it should be tested on /survival.

**Comment by TomLewis** [comment]
Idiots, this is most likely intended to stop duplication.
This sounds like a feature not a bug, and it sounds like player was testing to see if it duped it, playername?

**Comment by CreatingWithKass** [comment]
> Idiots, this is most likely intended to stop duplication.
> This sounds like a feature not a bug, and it sounds like player was testing to see if it duped it, playername?

The player that reported it was Nick_A_Naut, I believe he placed the shulker originally and then went to open the door later and it glitched out. I'll let him know it's a protection feature.

**Comment by TomLewis** [comment]
👍 No sweat then, but yeah, this sounds like protection from duplicating blocks/chests.
