### ISSUE TITLE
Missive explains that Contributors are able to rent up to 4 shops, which is not the case anymore. (harbinger787)

### ISSUE THREAD

**Issue by CreatingWithKass** [PirateCraft/dev#67]
**Describe the bug** *(A clear and concise description of what the bug is)*:
The Missive cycle still says that contributors are able to rent up to four shops, which is no longer the case. The message should be removed to avoid confusion. 

**To Reproduce** *(Steps to reproduce the behavior)*:
Watch the Missive messages cycle. It'll eventually pop up this message: "Contributor ranks can rent up to 4 shops!" 

**Time and Date** *(If applicable, add the time (in GMT+1) and date (DD.MM.YYYY) of the issue)*:
29/9/2020 (I realized I've been doing the dates wrong... dumb American moment) 2:54 A.M. GMT+1 

**Screenshots/Videos (Delete if not needed)** *(If applicable, add screenshots/videos to help explain your problem)*:
![missivebad](https://user-images.githubusercontent.com/69595267/94838559-c86d5500-03e3-11eb-9d3b-27ab3104a379.jpg)

**Comment by TomLewis** [comment]
False advertising! Get your pitchforks!

Ok removed & Fixed.
