### ISSUE TITLE
This sign at /warp travel spells "you" like "yuo" (Solembus13 reported) 

### ISSUE THREAD

**Issue by CreatingWithKass** [PirateCraft/dev#69]
**Describe the bug** *(A clear and concise description of what the bug is)*:
This sign misspells "you" as "yuo" at /warp travel. 

**To Reproduce** *(Steps to reproduce the behavior)*:
Do /warp travel. One of the signs on the spawning platform has the typo. 

**Time and Date** *(If applicable, add the time (in GMT+1) and date (DD.MM.YYYY) of the issue)*:
3/10/2020 7:34 P.M. GMT+1 

**Screenshots/Videos (Delete if not needed)** *(If applicable, add screenshots/videos to help explain your problem)*:
![yuo](https://user-images.githubusercontent.com/69595267/95000453-f80c9080-058e-11eb-8660-094fc150bdf7.png)

**Comment by Markusi13** [comment]
Fixed.
