### ISSUE TITLE
You can't use any part of a username other than the first few letters anymore to /msg someone

### ISSUE THREAD

**Issue by Markusi13** [PirateCraft/dev#7]
**Describe the bug** *(A clear and concise description of what the bug is)*:
When trying to message ministermoo for example you can't type /msg moo inorder to message him. You'll have to either use /msg minister or the full name. 

**To Reproduce** *(Steps to reproduce the behavior)*:
Try messaging someone with /msg using any part other of their name other than the first few letters/words.

**Time and Date** *(If applicable, add the time (in GMT+1) and date (DD.MM.YYYY) of the issue)*:
11.08.2020 | 22:42

**Additional context (Delete if this isn't needed)** *(Add any other context about the problem here)*:
This has been reported by cysteen. She says that it was apparently possible before we switched hosts. Her request:
`Basically im asking if there is a way to fix so you may type /m and any part of someone name to start a dm, instead of the first letters? it isnt urgent, but a slight inconvinience once you get accustomed to typing out a message to someone a certain way haha`

**Comment by FrozenBeard** [comment]
Just tested with everyone online, works fine.
