### ISSUE TITLE
The BOTM missive is still for September and needs to be updated to October. 

### ISSUE THREAD

**Issue by CreatingWithKass** [PirateCraft/dev#72]
**Describe the bug** *(A clear and concise description of what the bug is)*:
The Missive message for BOTM is still set for September and needs to be updated to October. 

**To Reproduce** *(Steps to reproduce the behavior)*:
Watch the missive cycle. 

**Time and Date** *(If applicable, add the time (in GMT+1) and date (DD.MM.YYYY) of the issue)*:
11/10/2020 | 7:39 a.m. 

**Screenshots/Videos (Delete if not needed)** *(If applicable, add screenshots/videos to help explain your problem)*:
![itsoctober](https://user-images.githubusercontent.com/69595267/95699016-65649500-0c11-11eb-9032-4f389a22996e.png)

**Comment by TomLewis** [comment]
Finally removed lol thanks!
