### ISSUE TITLE
If more than 28 levers are hooked up to a device sign, the server will kick them for "Illegal Interaction with a block"(_Augustus_Caesar) 

### ISSUE THREAD

**Issue by CreatingWithKass** [PirateCraft/dev#73]
**Describe the bug** *(A clear and concise description of what the bug is)*:
When a player connects more than 28 levers to a device sign, they are immediately kicked for "illegal interaction with a block", and can't rejoin again for 8 seconds. 

**To Reproduce** *(Steps to reproduce the behavior)*:
Create a device sign and try to hook up more than 28 levers; it'll kick you. 

**Time and Date** *(If applicable, add the time (in GMT+1) and date (DD.MM.YYYY) of the issue)*:
13/10/2020 10:51 P.M. GMT+1
**Screenshots/Videos (Delete if not needed)** *(If applicable, add screenshots/videos to help explain your problem)*:
https://www.youtube.com/watch?v=PyM253ki7qc

**Comment by TomLewis** [comment]
**28 Levers**! What! I assumed you could only connect one! Who is using 28 Levers wireless and what for?
This seems like a god damn feature protecting us!

**Comment by CreatingWithKass** [comment]
> **28 Levers**! What! I assumed you could only connect one! Who is using 28 Levers wireless and what for?
> This seems like a god damn feature protecting us!

LOL It was PIP that reported it. I thought 28 was one hell of a number too.

**Comment by TomLewis** [comment]
Yeah, im going to say this is a bug, but I cant get it fixed as wireless redstone is from the Shop plugin, which the developer is, 1 a massive asshole and 2 he does not fix bugs, let alone backdate to 1.12.2, so this is just insane use of something. If it works with 1 then thats how its intended to be used!
