### ISSUE TITLE
Some 1.16.2-3 players' Minecrafts completely crash when crafting, especially when using the inventory crafting 4x4. (Espul)

### ISSUE THREAD

**Issue by CreatingWithKass** [PirateCraft/dev#74]
**Describe the bug** *(A clear and concise description of what the bug is)*:
At random players in 1.16.2 or 3 are kicked from the server because their games completely crash while on PMC - we need a LOT more information but I thought it should be brought to the Github. Not sure if it is the server or just their games, as it crashes the entire game, but has been happening to a few players now. 

**To Reproduce** *(Steps to reproduce the behavior)*:
Near impossible to reproduce as it happens at random. Be in 1.16.2-3 and try to craft, especially in the 4x4 crafting menu in your inventory. Your game might completely crash. 

**Time and Date** *(If applicable, add the time (in GMT+1) and date (**DD.MM.YYYY**) of the issue)*:
11/10/2020 7:39 A.M. GMT+1

**Comment by TomLewis** [comment]
Minecraft records crash logs, these people that have crashes if they post their crash logs, it should give us an indication why.
Either in `.minecraft/crash-reports` or `.minecraft\logs\` Get those posted here and we can have a look.

**Comment by CreatingWithKass** [comment]
The game crashed whilst rendering screen
Error: java.lang.NullPointerException: Rendering screen
Exit Code: -1

- khaiethan

**Comment by TomLewis** [comment]
> 
> 
> The game crashed whilst rendering screen
> Error: java.lang.NullPointerException: Rendering screen
> Exit Code: -1
> 
>     * khaiethan

Not related to piratecraft then.
