### ISSUE TITLE
The new "Combat Mode" 15 second bossbar shows up whenever you hit a mob, not just a player. (Gqldenn)

### ISSUE THREAD

**Issue by CreatingWithKass** [PirateCraft/dev#75]
**Describe the bug** *(A clear and concise description of what the bug is)*:
When a player hits any mob (hostile & passive), a combat tag pops up like when a player tags another player. The player can still TP and log when tagged by a Minecraft mob, however two bars pop up if a player hits another player (one at the top of the screen and one above the XP bar). 

**To Reproduce** *(Steps to reproduce the behavior)*:
Hit a hostile or passive mob. A combat bar will pop up indicating that you're in combat. It happens when the player hits another player as well, causing two combat log indications to pop up (one at the top of the screen and one above the XP bar). 

**Time and Date** *(If applicable, add the time (in GMT+1) and date (DD.MM.YYYY) of the issue)*:
15/10/2020 4:31 a.m. GMT+1

**Comment by TomLewis** [comment]
Premium Essentails plugin added his own Combat timer, so 2 were being used.
