### ISSUE TITLE
The new server play seems to be made for 1.8. The bot spam clicks, and the potions seem to be more of a 1.8 ideal rather than 1.12.

### ISSUE THREAD

**Issue by CreatingWithKass** [PirateCraft/dev#76]
**Describe the bug** *(A clear and concise description of what the bug is)*:
The PVP bot spam-clicks like 1.8 combat where the server is in 1.9 combat. It should probably be updated to match the server's PVP style. 

**To Reproduce** *(Steps to reproduce the behavior)*:
Go to the PvP test map and mess with the bot. It spam clicks and is therefore easy to kill. 

**Time and Date** *(If applicable, add the time (in GMT+1) and date (DD.MM.YYYY) of the issue)*:
19/10/2020 8:16 P.M. GMT+1

**Comment by TomLewis** [comment]
The play server isnt for 1.8, just the bot is very basic.
