### ISSUE TITLE
A lot of /crew commands don't work for random players at random times. 

### ISSUE THREAD

**Issue by CreatingWithKass** [PirateCraft/dev#77]
**Describe the bug** *(A clear and concise description of what the bug is)*:
I'm sure you know about this, but I'll add it to the Git to keep track. A lot of /crew commands don't work for random players at random times, but work for others. Here's an example of the message that sometimes pops up. 

**To Reproduce** *(Steps to reproduce the behavior)*:

**Time and Date** *(If applicable, add the time (in GMT+1) and date (DD.MM.YYYY) of the issue)*:
19/10/2020 9:56 P.M. GMT+1

**Screenshots/Videos (Delete if not needed)** *(If applicable, add screenshots/videos to help explain your problem)*:
![buuuugs](https://user-images.githubusercontent.com/69595267/97063854-1f43f580-1570-11eb-8d81-96e2be3cb4ef.png)

**Comment by TomLewis** [comment]
This is 99% players not understanding that the crew plugin has updated and these commands no longer exist, its all within a gui now /crew.

People keep trying to use old commands that no longer work as they used to.

This is player not server.
