### ISSUE TITLE
Certain blocks refuse to update in /creative. 

### ISSUE THREAD

**Issue by CreatingWithKass** [PirateCraft/dev#78]
**Describe the bug** *(A clear and concise description of what the bug is)*:
Blocks such as buttons, torches, signs, water, etc refusing to update on Creative.

**To Reproduce** *(Steps to reproduce the behavior)*:
Place a button on a block, break the block, button most likely will stay in place.

**Time and Date** *(If applicable, add the time (in GMT+1) and date (DD.MM.YYYY) of the issue)*:
23/10/2020 5:51 P.M. GMT+1 

**Screenshots/Videos (Delete if not needed)** *(If applicable, add screenshots/videos to help explain your problem)*:
![bugg](https://user-images.githubusercontent.com/69595267/97064084-a04fbc80-1571-11eb-8e6c-27d2ce039e5b.png)

**Comment by TomLewis** [comment]
This is just worldedit, its always done this. Break the floating blocks by hand.
Never figured it out.

ideas;

1. It could be Worldedit just not working with these items.
2. it could be FAWE screwing with WE
3. It could be WorldGuard somehow protecting these

Not worth the time to figure out, as its always done this on both Survival/Test/Local/Creative Its just a WE issue you need to live with.

Labelled wontfix as I dont know what causes it.
