### ISSUE TITLE
[Donate] seems to glitch and causes a partial stack of items in your inventory to disappear instead of going in the chest if the player also has a partial/full stack in their off-hand. (Capt_Lugnut)

### ISSUE THREAD

**Issue by CreatingWithKass** [PirateCraft/dev#79]
**Describe the bug** *(A clear and concise description of what the bug is)*:
When using a [donate] sign for multiple items, if you have a partial stack of items in your inventory and partial/full stack in your off hand. (or any combination that totals at least what the sign is calling for, but not double or more) It will delete the partial stack in your inventory, not transferring them to a chest, and then give you an error "[Sign Shop] Could not complete operation, contact your System Administrator and checks the logs."
It seems the plug in can see to check and pass, that you have the right amount of items, but just gets hung up trying to pull items from the off hand slot. a Pre 1.9 plug in, missing a slot 45 in there somewhere, maybe?

**To Reproduce** *(Steps to reproduce the behavior)*:
Try to use a [donate] sign for multiple items while holding a partial stack of an item in your hand with another partial stack in your offhand. The one in your main hand might disappear instead of going into the chest, and you will receive an error message. 

**Time and Date** *(If applicable, add the time (in GMT+1) and date (DD.MM.YYYY) of the issue)*:
2310/2020 11:01 P.M. GMT+1

**Comment by TomLewis** [comment]
I think the plugin was made before offhand existed.

**Comment by TomLewis** [comment]
im going to set wontfix just because the developer wont fix anything for older minecraft versions, once we update to 1.13+ and update the shop plugin, re-open this ticket if its still an issue, I cant resolve this as it stands.
