### ISSUE TITLE
Unable to set coloured crew rank display names (Enderzalt)

### ISSUE THREAD

**Issue by IwanIDev** [PirateCraft/dev#80]
**Describe the bug** *(A clear and concise description of what the bug is)*:
When attempting to set the display name of a crew rank, the error _"You cannot set colored ranks"_ appears. Players are able to set the display name of a crew rank without problems when not using colour codes.

**To Reproduce** *(Steps to reproduce the behavior)*:
1. Create a crew rank
2. Attempt to modify the display name of that rank, for example _/crew rank setdisplayname cosmic &4&lImperator_

**Time and Date** *(If applicable, add the time (in GMT+1) and date (DD.MM.YYYY) of the issue)*:
24.10.2020 19:11

**Comment by TomLewis** [comment]
This is a captain only perk.

**Comment by enderzalt** [comment]
As far as I am aware, setting crew ranks with color was allowed for everyone (maybe you're getting confused with /crew modtag?), and besides, I have captain and it still did not work. Can you relook at this?

- Thanks, Enderzalt
(I was told to make this comment by LEGQ, not exactly sure how this works lol)

**Comment by IwanIDev** [comment]
Reopened, reporter forgot to mention that they are a captain rank and yet the bug persists.

**Comment by TomLewis** [comment]
So what is it? @enderzalt said they fixed it in game?

is this a bug or not?

**Comment by enderzalt** [comment]
Yes, it is still a bug. I said it poorly in the edit, I apologize. I meant to just ignore that comment as this thread would be reopened after the original mistake. 

(expecting to get yelled at for this lol im an idiot)

**Comment by CreatingWithKass** [comment]
@TomLewis It's still a bug, no one can set colored crew ranks, even if they are captain.

**Comment by TomLewis** [comment]
Oh sorry, I read it as Crew Color, not Crew rank, skim reading.

I would assume when we updated to the new Ranks system that there was a new way in saving crew rank names, I will create a ticket.

**Comment by TomLewis** [comment]
Fixed.
