### ISSUE TITLE
Donation Page of deadmans keys doesnt work, blank page opens.

### ISSUE THREAD

**Issue by CrazyMoneyy** [PirateCraft/dev#82]
**Describe the bug** *(A clear and concise description of what the bug is)*:
The Deadmans Keys on the donation page from mc.piratemc.com doesnt work. Wanting to purchase some keys gives a blank white page doing nothing else. Other pages like ranks seems to be working.

**To Reproduce** *(Steps to reproduce the behavior)*:
Open the PMC site and try to buy the keys. It gives a blank page.

**Time and Date** *(If applicable, add the time (in GMT+1) and date (DD.MM.YYYY) of the issue)*:
25-10-2020 16:57

**Comment by TomLewis** [comment]
I need to get my re-design live for the store live, this shti is legacy for like 2 years haha 
oh dear, reminder to me to get shit done. 2 years since the redesign
