### ISSUE TITLE
Slimes not spawning (Simbud)

### ISSUE THREAD

**Issue by IwanIDev** [PirateCraft/dev#83]
**Describe the bug** *(A clear and concise description of what the bug is)*:
Slimes are no longer spawning in slimechunks. Usually, slimes will periodically spawn in these areas, however now they are no longer doing so.

**To Reproduce** *(Steps to reproduce the behavior)*:
1. Travel to an area where slimes usually spawn
2. Observe the lack of slimes spawning

**Time and Date** *(If applicable, add the time (in GMT+1) and date (DD.MM.YYYY) of the issue)*:
28.10.2020 10:01 (GMT+1)

**Comment by TomLewis** [comment]
Only possible thing would be the entity manager, I checked and slimes are only limited with other monsters to 30 per chunk.

I would gander that the user isn't in a slime chunk, this report has not included the teleport coordinates for the chunk to check.

This needs to be confirmed, sounds like user error and not a bug.
