### ISSUE TITLE
Punishment Tracker not updating (Kangy_Roo)

### ISSUE THREAD

**Issue by IwanIDev** [PirateCraft/dev#84]
**Describe the bug** *(A clear and concise description of what the bug is)*:
Punishment tracker (https://bans.piratemc.com/) is not showing any punishments after the 18th October. Presumably there have been punishments since that date, however none appear on the page.

**To Reproduce** *(Steps to reproduce the behavior)*:
1. Go to https://bans.piratemc.com/
2. Look at the latest punishments shown, should show only punishments from over 10 days ago (at time of writing)

**Time and Date** *(If applicable, add the time (in GMT+1) and date (DD.MM.YYYY) of the issue)*:
First reported 27.10.2020 at 11:55 (GMT+1)

**Comment by TomLewis** [comment]
Day before my birthday, I changed the script and never tested it trying to reduce the size of my backups!
I had years of the database backups, itll be something in my backup script that broke then.

**Comment by TomLewis** [comment]
ok fixed!
I moved variables to a config file but the script wasn't loading bash so `source` wasnt working.

Just dont a manual update.
