### ISSUE TITLE
/crew bb posts only allow 1 word (Kangy_Roo)

### ISSUE THREAD

**Issue by IwanIDev** [PirateCraft/dev#85]
**Describe the bug** *(A clear and concise description of what the bug is)*:
When posting a message to your /crew bb, you are not able to post unless there are no spaces in your message.

**To Reproduce** *(Steps to reproduce the behavior)*:
1. Attempt to post a message with spaces to the /crew bb
2. Observe

**Time and Date** *(If applicable, add the time (in GMT+1) and date (DD.MM.YYYY) of the issue)*:
First reported 28.10.2020 at 01:07 (GMT+1)

**Comment by TomLewis** [comment]
Ha, I bet this is from me requesting ranks not have spaces in them.

**Comment by RoinujNosde** [comment]
> Ha, I bet this is from me requesting ranks not have spaces in them.

It's not haha

**Comment by TomLewis** [comment]
Aha worth a guess! haha
