### ISSUE TITLE
Test server reverting people to sailor rank (TheTikiTotem)

### ISSUE THREAD

**Issue by IwanIDev** [PirateCraft/dev#86]
**Describe the bug** *(A clear and concise description of what the bug is)*:
After logging into the test server, people are being informed that they have ranked up to sailor rank, even though they had a higher rank previously. This then causes their rank to change to sailor on the survival server also.

**To Reproduce** *(Steps to reproduce the behavior)*:
1. Log onto test server
2. Check your rank (should have changed to sailor rank)
3. Go back to survival and check rank (should also be sailor)

**Time and Date** *(If applicable, add the time (in GMT+1) and date (DD.MM.YYYY) of the issue)*:
First reported 31.10.2020 at 16:49 (GMT+1)

**Comment by IwanIDev** [comment]
![Image of bug](https://cdn.discordapp.com/attachments/772414763829297152/772414795323277322/2020-11-01_21.58.06.png)

Example of it changing people's ranks.

**Comment by TomLewis** [comment]
Disabled, people that are still effected will need to PM me.
