### ISSUE TITLE
If a player repeatedly clicks a toggle sign they're kicked. (RoMich) 

### ISSUE THREAD

**Issue by CreatingWithKass** [PirateCraft/dev#89]
**Describe the bug** *(A clear and concise description of what the bug is)*:
If a player repeatedly clicks a toggle sign, they're ultimately kicked for unusually interacting with blocks or entities. 

**To Reproduce** *(Steps to reproduce the behavior)*:
Repeatedly click a toggle sign. It will kick you for illegally interacting with blocks or entities. 

**Time and Date** *(If applicable, add the time (in GMT+1) and date (DD.MM.YYYY) of the issue)*:
31/10/2020 8:45 P.M. GMT+1 

**Screenshots/Videos (Delete if not needed)** *(If applicable, add screenshots/videos to help explain your problem)*:
https://www.youtube.com/watch?v=hd42R9Ci-w8

**Additional context (Delete if this isn't needed)** *(Add any other context about the problem here)*:
**This might be similar to the other bug report, about being kicked for connecting too many levers, so it could be a protection mechanism. I will post it just in case.**

**Comment by TomLewis** [comment]
1. What version of Minecraft are they using?
2. Does this also happen if you don't have something in your offhand? Could this be related to Signshop & Offhand bug #79

**Comment by CreatingWithKass** [comment]
> 1. What version of Minecraft are they using?
> 2. Does this also happen if you don't have something in your offhand? Could this be related to Signshop & Offhand bug #79

**RoMich tested these questions and here are his results:**
1. In 1.13+ it happens 
2. It happens even without items in second hand
