### ISSUE TITLE
The command /depositall doesn't deposit arrows.

### ISSUE THREAD

**Issue by Markusi13** [PirateCraft/dev#9]
**Describe the bug** *(A clear and concise description of what the bug is)*:
When you have unnamed arrows in a chest and you also have unnamed arrows in your inventory and you type /depositall next to the chest, it doesn't actually deposit the arrows into the chest. It just says `Deposited 0 items into nearby chests.`

**To Reproduce** *(Steps to reproduce the behavior)*:
Have some unnamed arrows in a nearby chest and in your inventory and type /depositall while standing next to the chest.

**Time and Date** *(If applicable, add the time (in GMT+1) and date (DD.MM.YYYY) of the issue)*:
12.08.2020 | 11:17

**Comment by FrozenBeard** [comment]
Plugin will require changing entirely when we go 1.13+
