### ISSUE TITLE
When a player does /parrots to pull up the parrot menu, the gray parrot still says 'red parrot' in the description. 

### ISSUE THREAD

**Issue by CreatingWithKass** [PirateCraft/dev#93]
**Describe the bug** *(A clear and concise description of what the bug is)*:
Simply a typo, the parrots in /parrots all have proper colors in their description except for the gray one. When hovering over the gray parrot icon, it says "red parrot" instead. 
Also, for consistency reasons, the Blue Parrot is written in green, as seen in the image below. Could be changed to dark blue to follow the rest of the parrots, but that's up to you :) 

**To Reproduce** *(Steps to reproduce the behavior)*:
Do /parrots while in-game. You'll see the gray parrot has an improper description color. 

**Time and Date** *(If applicable, add the time (in GMT+1) and date (DD.MM.YYYY) of the issue)*:
16/11/2020 

**Screenshots/Videos (Delete if not needed)** *(If applicable, add screenshots/videos to help explain your problem)*:
![parrots](https://user-images.githubusercontent.com/69595267/99709204-e0209b80-2a6c-11eb-872c-6f359da96b65.png)
![parrots2](https://user-images.githubusercontent.com/69595267/99709220-e4e54f80-2a6c-11eb-882a-8a0ec6a1ecb1.png)

**Comment by TomLewis** [comment]
Fixed!
