### ISSUE TITLE
**This is actually a /server play issue** When using commands on /server play, I get kicked for spamming. (ViaVersion Tab Issue) ((khaiethan))

### ISSUE THREAD

**Issue by CreatingWithKass** [PirateCraft/dev#94]
**Describe the bug** *(A clear and concise description of what the bug is)*:
When a player tries to /msg other players inside of /server play, they get kicked for spamming. Seems to happen with some other commands as well. 

**To Reproduce** *(Steps to reproduce the behavior)*:
Go to /server play and start trying to do commands (such as /msg) within that server. It will sometimes kick for spamming when you try to do commands. 

**Time and Date** *(If applicable, add the time (in GMT+1) and date (DD.MM.YYYY) of the issue)*:
8:37 PM GMT+1 20/11/2020

**Comment by TomLewis** [comment]
Set `disable-1_13-auto-complete` to true in Play. Done!
