### ISSUE TITLE
When donation ranks run out and the server sends the player mail, it still appears using the old mail system, not the new one. (Kangy_Roo)

### ISSUE THREAD

**Issue by CreatingWithKass** [PirateCraft/dev#95]
**Describe the bug** *(A clear and concise description of what the bug is)*:
When players donate, they receive an automated /mail msg from the server. The same happens when their rank runs out of time, reminding them that the rank has expired. It still sends this msg to the old mail system, not the new one. 

**To Reproduce** *(Steps to reproduce the behavior)*:
Lose a donation rank, the mail received will be in the old mailing sysem. 
10:39 P.M. GMT+1 18/11/2020 

Time: 
10:39 P.M. GMT+1 18/11/2020

**Comment by TomLewis** [comment]
Ha, oh yeah. How annoying. 
Fixed for Ranks, I've fixed it as a global command that's sent for any package that runs out, incase we add any more temporary things to the store. (One command to update instead of 3)
