### ISSUE TITLE
Rankup message showing wrong username (Tulipss)

### ISSUE THREAD

**Issue by IwanIDev** [PirateCraft/dev#96]
**Describe the bug** *(A clear and concise description of what the bug is)*:
When ranking up (quartermaster in reported case) the _"Congratulations..."_ message shows the username of a different user. In the reported incident, the user Tulipss ranked up to Quartermaster, however the message showed the username trooper306, however the public _Broadcast_ message shows the correct username. The user who was shown incorrectly was not online at the time.

**To Reproduce** *(Steps to reproduce the behavior)*:
1. Achieve all rankup requirements.
2. Run the /rankup command

**Time and Date** *(If applicable, add the time (in GMT+1) and date (DD.MM.YYYY) of the issue)*:
First reported 25.11.2020 at 19:53 GMT+1 

**Screenshots/Videos (Delete if not needed)** *(If applicable, add screenshots/videos to help explain your problem)*:
(accidentally lost the image, whoops)

**Comment by TomLewis** [comment]
Not sure. The configs are fine as theres only 1 parameter for player name. Must be in his Logic for the plugin.
I will be replacing this Ranking system in the future so not worth looking into a fix.
