### ISSUE TITLE
/rankup message for Firtmate and Quartermaster is wrong, showing the incorrect number for the EXP boost and a wrong time for how long it lasts (khaiethan)

### ISSUE THREAD

**Issue by CreatingWithKass** [PirateCraft/dev#97]
**Describe the bug** *(A clear and concise description of what the bug is)*:
The Chat displays a '2.0x XP booster for 2 hours' for Firstmate rankup. However, in practice this is a 2.5x boost. The time also seems incorrect as I believe it said 2 hours on the message in chat, but it is actually for 5 hours (18000 second boost from /xpb info) 
**This might be the same for Quartermaster, double check** 

**To Reproduce** *(Steps to reproduce the behavior)*:
Someone has to rankup in chat to Firstmate. It'll show a message explaining that they get an EXP boost and for how long, but both numbers are wrong. 

**Time and Date** *(If applicable, add the time (in GMT+1) and date (DD.MM.YYYY) of the issue)*:
25/11/2020 3:45 P.M. GMT+1

**Comment by TomLewis** [comment]
oh yeah it was way off, saying 2 hours instead of 12 hours haha
This is me just copy/pasting from the old rank when I made it! 

Fixed both messages.
