### ISSUE TITLE
 Stockman at /warp south doesn't sell donkeys/mules. (M00SE_CABOOSE)

### ISSUE THREAD

**Issue by CrazyMoneyy** [PirateCraft/dev#98]
**Describe the bug** *(A clear and concise description of what the bug is)*:
The Stockman that sells horses and donkeys/mules at /warp south doesn't sell the donkeys and mules anymore.  I think this might have to do with the dupping glitches that they have been disabled. If so than this is not the priority I guess.

**To Reproduce** *(Steps to reproduce the behavior)*:
Try to buy a mule or donkey from /warp south's stockman

**Time and Date** *(If applicable, add the time (in GMT+1) and date (DD.MM.YYYY) of the issue)*:
19:17 6-12-2020

**Screenshots/Videos (Delete if not needed)** *(If applicable, add screenshots/videos to help explain your problem)*:
![image](https://user-images.githubusercontent.com/69697407/101290123-a687b880-3800-11eb-96f7-717033f91891.png)

**Additional context (Delete if this isn't needed)** *(Add any other context about the problem here)*:
If they were disabled, probably best to ignore this bugreport.

**Comment by TomLewis** [comment]
I disabled them on purpose because of a dupe glitch.
They were also removed from the store & can no longer be spawned. 
I would appreciate if this information was kept quiet (Don't go blabbing about it).
