### ISSUE TITLE
Kicked whilst breaking ice and walking backwards (DeimosWreck)

### ISSUE THREAD

**Issue by IwanIDev** [PirateCraft/dev#99]
**Describe the bug** *(A clear and concise description of what the bug is)*:
When breaking ice and walking backwards (video is easier to explain), you can get kicked for "Combat Hacks". This may only be an issue with 1.15.2 clients (since they are quite unstable).

**To Reproduce** *(Steps to reproduce the behavior)*:
1. Place a row of ice
2. Run down it backwards, whilst breaking ice

**Time and Date** *(If applicable, add the time (in GMT+1) and date (DD.MM.YYYY) of the issue)*:
First reported 4.12.2020 at 12:05 GMT+1

**Screenshots/Videos (Delete if not needed)** *(If applicable, add screenshots/videos to help explain your problem)*:
Video link https://cdn.discordapp.com/attachments/744927959764434974/784375472019996692/Minecraft__1.15.2_-_Multijugador_de_terceros_2020-12-04_11-55-58_Trim_3.mp4

**Comment by TomLewis** [comment]
@Encode42

**Comment by Encode42** [comment]
@IwanIDev is this still an issue? The anticheat has been updated multiple times since the report was made; I believe it should be taken care of now.

**Comment by TomLewis** [comment]
@IwanIDev can you ping DeimosWreck to check this again please.
